// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cosmos/base/snapshots/v1beta1/snapshot.proto

package cosmos.base.snapshots.v1beta1;

public final class SnapshotOuterClass {
  private SnapshotOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SnapshotOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cosmos.base.snapshots.v1beta1.Snapshot)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional uint64 height = 1;</code>
     */
    long getHeight();

    /**
     * <code>optional uint32 format = 2;</code>
     */
    int getFormat();

    /**
     * <code>optional uint32 chunks = 3;</code>
     */
    int getChunks();

    /**
     * <code>optional bytes hash = 4;</code>
     */
    com.google.protobuf.ByteString getHash();

    /**
     * <code>optional .cosmos.base.snapshots.v1beta1.Metadata metadata = 5;</code>
     */
    boolean hasMetadata();
    /**
     * <code>optional .cosmos.base.snapshots.v1beta1.Metadata metadata = 5;</code>
     */
    cosmos.base.snapshots.v1beta1.SnapshotOuterClass.Metadata getMetadata();
    /**
     * <code>optional .cosmos.base.snapshots.v1beta1.Metadata metadata = 5;</code>
     */
    cosmos.base.snapshots.v1beta1.SnapshotOuterClass.MetadataOrBuilder getMetadataOrBuilder();
  }
  /**
   * <pre>
   * Snapshot contains Tendermint state sync snapshot info.
   * </pre>
   *
   * Protobuf type {@code cosmos.base.snapshots.v1beta1.Snapshot}
   */
  public  static final class Snapshot extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cosmos.base.snapshots.v1beta1.Snapshot)
      SnapshotOrBuilder {
    // Use Snapshot.newBuilder() to construct.
    private Snapshot(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Snapshot() {
      height_ = 0L;
      format_ = 0;
      chunks_ = 0;
      hash_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Snapshot(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              height_ = input.readUInt64();
              break;
            }
            case 16: {

              format_ = input.readUInt32();
              break;
            }
            case 24: {

              chunks_ = input.readUInt32();
              break;
            }
            case 34: {

              hash_ = input.readBytes();
              break;
            }
            case 42: {
              cosmos.base.snapshots.v1beta1.SnapshotOuterClass.Metadata.Builder subBuilder = null;
              if (metadata_ != null) {
                subBuilder = metadata_.toBuilder();
              }
              metadata_ = input.readMessage(cosmos.base.snapshots.v1beta1.SnapshotOuterClass.Metadata.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(metadata_);
                metadata_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cosmos.base.snapshots.v1beta1.SnapshotOuterClass.internal_static_cosmos_base_snapshots_v1beta1_Snapshot_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cosmos.base.snapshots.v1beta1.SnapshotOuterClass.internal_static_cosmos_base_snapshots_v1beta1_Snapshot_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cosmos.base.snapshots.v1beta1.SnapshotOuterClass.Snapshot.class, cosmos.base.snapshots.v1beta1.SnapshotOuterClass.Snapshot.Builder.class);
    }

    public static final int HEIGHT_FIELD_NUMBER = 1;
    private long height_;
    /**
     * <code>optional uint64 height = 1;</code>
     */
    public long getHeight() {
      return height_;
    }

    public static final int FORMAT_FIELD_NUMBER = 2;
    private int format_;
    /**
     * <code>optional uint32 format = 2;</code>
     */
    public int getFormat() {
      return format_;
    }

    public static final int CHUNKS_FIELD_NUMBER = 3;
    private int chunks_;
    /**
     * <code>optional uint32 chunks = 3;</code>
     */
    public int getChunks() {
      return chunks_;
    }

    public static final int HASH_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString hash_;
    /**
     * <code>optional bytes hash = 4;</code>
     */
    public com.google.protobuf.ByteString getHash() {
      return hash_;
    }

    public static final int METADATA_FIELD_NUMBER = 5;
    private cosmos.base.snapshots.v1beta1.SnapshotOuterClass.Metadata metadata_;
    /**
     * <code>optional .cosmos.base.snapshots.v1beta1.Metadata metadata = 5;</code>
     */
    public boolean hasMetadata() {
      return metadata_ != null;
    }
    /**
     * <code>optional .cosmos.base.snapshots.v1beta1.Metadata metadata = 5;</code>
     */
    public cosmos.base.snapshots.v1beta1.SnapshotOuterClass.Metadata getMetadata() {
      return metadata_ == null ? cosmos.base.snapshots.v1beta1.SnapshotOuterClass.Metadata.getDefaultInstance() : metadata_;
    }
    /**
     * <code>optional .cosmos.base.snapshots.v1beta1.Metadata metadata = 5;</code>
     */
    public cosmos.base.snapshots.v1beta1.SnapshotOuterClass.MetadataOrBuilder getMetadataOrBuilder() {
      return getMetadata();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (height_ != 0L) {
        output.writeUInt64(1, height_);
      }
      if (format_ != 0) {
        output.writeUInt32(2, format_);
      }
      if (chunks_ != 0) {
        output.writeUInt32(3, chunks_);
      }
      if (!hash_.isEmpty()) {
        output.writeBytes(4, hash_);
      }
      if (metadata_ != null) {
        output.writeMessage(5, getMetadata());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (height_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, height_);
      }
      if (format_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, format_);
      }
      if (chunks_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, chunks_);
      }
      if (!hash_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, hash_);
      }
      if (metadata_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getMetadata());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cosmos.base.snapshots.v1beta1.SnapshotOuterClass.Snapshot)) {
        return super.equals(obj);
      }
      cosmos.base.snapshots.v1beta1.SnapshotOuterClass.Snapshot other = (cosmos.base.snapshots.v1beta1.SnapshotOuterClass.Snapshot) obj;

      boolean result = true;
      result = result && (getHeight()
          == other.getHeight());
      result = result && (getFormat()
          == other.getFormat());
      result = result && (getChunks()
          == other.getChunks());
      result = result && getHash()
          .equals(other.getHash());
      result = result && (hasMetadata() == other.hasMetadata());
      if (hasMetadata()) {
        result = result && getMetadata()
            .equals(other.getMetadata());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + HEIGHT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getHeight());
      hash = (37 * hash) + FORMAT_FIELD_NUMBER;
      hash = (53 * hash) + getFormat();
      hash = (37 * hash) + CHUNKS_FIELD_NUMBER;
      hash = (53 * hash) + getChunks();
      hash = (37 * hash) + HASH_FIELD_NUMBER;
      hash = (53 * hash) + getHash().hashCode();
      if (hasMetadata()) {
        hash = (37 * hash) + METADATA_FIELD_NUMBER;
        hash = (53 * hash) + getMetadata().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cosmos.base.snapshots.v1beta1.SnapshotOuterClass.Snapshot parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cosmos.base.snapshots.v1beta1.SnapshotOuterClass.Snapshot parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cosmos.base.snapshots.v1beta1.SnapshotOuterClass.Snapshot parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cosmos.base.snapshots.v1beta1.SnapshotOuterClass.Snapshot parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cosmos.base.snapshots.v1beta1.SnapshotOuterClass.Snapshot parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cosmos.base.snapshots.v1beta1.SnapshotOuterClass.Snapshot parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cosmos.base.snapshots.v1beta1.SnapshotOuterClass.Snapshot parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cosmos.base.snapshots.v1beta1.SnapshotOuterClass.Snapshot parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cosmos.base.snapshots.v1beta1.SnapshotOuterClass.Snapshot parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cosmos.base.snapshots.v1beta1.SnapshotOuterClass.Snapshot parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cosmos.base.snapshots.v1beta1.SnapshotOuterClass.Snapshot prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Snapshot contains Tendermint state sync snapshot info.
     * </pre>
     *
     * Protobuf type {@code cosmos.base.snapshots.v1beta1.Snapshot}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cosmos.base.snapshots.v1beta1.Snapshot)
        cosmos.base.snapshots.v1beta1.SnapshotOuterClass.SnapshotOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cosmos.base.snapshots.v1beta1.SnapshotOuterClass.internal_static_cosmos_base_snapshots_v1beta1_Snapshot_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cosmos.base.snapshots.v1beta1.SnapshotOuterClass.internal_static_cosmos_base_snapshots_v1beta1_Snapshot_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cosmos.base.snapshots.v1beta1.SnapshotOuterClass.Snapshot.class, cosmos.base.snapshots.v1beta1.SnapshotOuterClass.Snapshot.Builder.class);
      }

      // Construct using cosmos.base.snapshots.v1beta1.SnapshotOuterClass.Snapshot.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        height_ = 0L;

        format_ = 0;

        chunks_ = 0;

        hash_ = com.google.protobuf.ByteString.EMPTY;

        if (metadataBuilder_ == null) {
          metadata_ = null;
        } else {
          metadata_ = null;
          metadataBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cosmos.base.snapshots.v1beta1.SnapshotOuterClass.internal_static_cosmos_base_snapshots_v1beta1_Snapshot_descriptor;
      }

      public cosmos.base.snapshots.v1beta1.SnapshotOuterClass.Snapshot getDefaultInstanceForType() {
        return cosmos.base.snapshots.v1beta1.SnapshotOuterClass.Snapshot.getDefaultInstance();
      }

      public cosmos.base.snapshots.v1beta1.SnapshotOuterClass.Snapshot build() {
        cosmos.base.snapshots.v1beta1.SnapshotOuterClass.Snapshot result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cosmos.base.snapshots.v1beta1.SnapshotOuterClass.Snapshot buildPartial() {
        cosmos.base.snapshots.v1beta1.SnapshotOuterClass.Snapshot result = new cosmos.base.snapshots.v1beta1.SnapshotOuterClass.Snapshot(this);
        result.height_ = height_;
        result.format_ = format_;
        result.chunks_ = chunks_;
        result.hash_ = hash_;
        if (metadataBuilder_ == null) {
          result.metadata_ = metadata_;
        } else {
          result.metadata_ = metadataBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cosmos.base.snapshots.v1beta1.SnapshotOuterClass.Snapshot) {
          return mergeFrom((cosmos.base.snapshots.v1beta1.SnapshotOuterClass.Snapshot)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cosmos.base.snapshots.v1beta1.SnapshotOuterClass.Snapshot other) {
        if (other == cosmos.base.snapshots.v1beta1.SnapshotOuterClass.Snapshot.getDefaultInstance()) return this;
        if (other.getHeight() != 0L) {
          setHeight(other.getHeight());
        }
        if (other.getFormat() != 0) {
          setFormat(other.getFormat());
        }
        if (other.getChunks() != 0) {
          setChunks(other.getChunks());
        }
        if (other.getHash() != com.google.protobuf.ByteString.EMPTY) {
          setHash(other.getHash());
        }
        if (other.hasMetadata()) {
          mergeMetadata(other.getMetadata());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cosmos.base.snapshots.v1beta1.SnapshotOuterClass.Snapshot parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cosmos.base.snapshots.v1beta1.SnapshotOuterClass.Snapshot) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long height_ ;
      /**
       * <code>optional uint64 height = 1;</code>
       */
      public long getHeight() {
        return height_;
      }
      /**
       * <code>optional uint64 height = 1;</code>
       */
      public Builder setHeight(long value) {
        
        height_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 height = 1;</code>
       */
      public Builder clearHeight() {
        
        height_ = 0L;
        onChanged();
        return this;
      }

      private int format_ ;
      /**
       * <code>optional uint32 format = 2;</code>
       */
      public int getFormat() {
        return format_;
      }
      /**
       * <code>optional uint32 format = 2;</code>
       */
      public Builder setFormat(int value) {
        
        format_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 format = 2;</code>
       */
      public Builder clearFormat() {
        
        format_ = 0;
        onChanged();
        return this;
      }

      private int chunks_ ;
      /**
       * <code>optional uint32 chunks = 3;</code>
       */
      public int getChunks() {
        return chunks_;
      }
      /**
       * <code>optional uint32 chunks = 3;</code>
       */
      public Builder setChunks(int value) {
        
        chunks_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 chunks = 3;</code>
       */
      public Builder clearChunks() {
        
        chunks_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString hash_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes hash = 4;</code>
       */
      public com.google.protobuf.ByteString getHash() {
        return hash_;
      }
      /**
       * <code>optional bytes hash = 4;</code>
       */
      public Builder setHash(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        hash_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes hash = 4;</code>
       */
      public Builder clearHash() {
        
        hash_ = getDefaultInstance().getHash();
        onChanged();
        return this;
      }

      private cosmos.base.snapshots.v1beta1.SnapshotOuterClass.Metadata metadata_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          cosmos.base.snapshots.v1beta1.SnapshotOuterClass.Metadata, cosmos.base.snapshots.v1beta1.SnapshotOuterClass.Metadata.Builder, cosmos.base.snapshots.v1beta1.SnapshotOuterClass.MetadataOrBuilder> metadataBuilder_;
      /**
       * <code>optional .cosmos.base.snapshots.v1beta1.Metadata metadata = 5;</code>
       */
      public boolean hasMetadata() {
        return metadataBuilder_ != null || metadata_ != null;
      }
      /**
       * <code>optional .cosmos.base.snapshots.v1beta1.Metadata metadata = 5;</code>
       */
      public cosmos.base.snapshots.v1beta1.SnapshotOuterClass.Metadata getMetadata() {
        if (metadataBuilder_ == null) {
          return metadata_ == null ? cosmos.base.snapshots.v1beta1.SnapshotOuterClass.Metadata.getDefaultInstance() : metadata_;
        } else {
          return metadataBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .cosmos.base.snapshots.v1beta1.Metadata metadata = 5;</code>
       */
      public Builder setMetadata(cosmos.base.snapshots.v1beta1.SnapshotOuterClass.Metadata value) {
        if (metadataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          metadata_ = value;
          onChanged();
        } else {
          metadataBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .cosmos.base.snapshots.v1beta1.Metadata metadata = 5;</code>
       */
      public Builder setMetadata(
          cosmos.base.snapshots.v1beta1.SnapshotOuterClass.Metadata.Builder builderForValue) {
        if (metadataBuilder_ == null) {
          metadata_ = builderForValue.build();
          onChanged();
        } else {
          metadataBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .cosmos.base.snapshots.v1beta1.Metadata metadata = 5;</code>
       */
      public Builder mergeMetadata(cosmos.base.snapshots.v1beta1.SnapshotOuterClass.Metadata value) {
        if (metadataBuilder_ == null) {
          if (metadata_ != null) {
            metadata_ =
              cosmos.base.snapshots.v1beta1.SnapshotOuterClass.Metadata.newBuilder(metadata_).mergeFrom(value).buildPartial();
          } else {
            metadata_ = value;
          }
          onChanged();
        } else {
          metadataBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .cosmos.base.snapshots.v1beta1.Metadata metadata = 5;</code>
       */
      public Builder clearMetadata() {
        if (metadataBuilder_ == null) {
          metadata_ = null;
          onChanged();
        } else {
          metadata_ = null;
          metadataBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .cosmos.base.snapshots.v1beta1.Metadata metadata = 5;</code>
       */
      public cosmos.base.snapshots.v1beta1.SnapshotOuterClass.Metadata.Builder getMetadataBuilder() {
        
        onChanged();
        return getMetadataFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .cosmos.base.snapshots.v1beta1.Metadata metadata = 5;</code>
       */
      public cosmos.base.snapshots.v1beta1.SnapshotOuterClass.MetadataOrBuilder getMetadataOrBuilder() {
        if (metadataBuilder_ != null) {
          return metadataBuilder_.getMessageOrBuilder();
        } else {
          return metadata_ == null ?
              cosmos.base.snapshots.v1beta1.SnapshotOuterClass.Metadata.getDefaultInstance() : metadata_;
        }
      }
      /**
       * <code>optional .cosmos.base.snapshots.v1beta1.Metadata metadata = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          cosmos.base.snapshots.v1beta1.SnapshotOuterClass.Metadata, cosmos.base.snapshots.v1beta1.SnapshotOuterClass.Metadata.Builder, cosmos.base.snapshots.v1beta1.SnapshotOuterClass.MetadataOrBuilder> 
          getMetadataFieldBuilder() {
        if (metadataBuilder_ == null) {
          metadataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              cosmos.base.snapshots.v1beta1.SnapshotOuterClass.Metadata, cosmos.base.snapshots.v1beta1.SnapshotOuterClass.Metadata.Builder, cosmos.base.snapshots.v1beta1.SnapshotOuterClass.MetadataOrBuilder>(
                  getMetadata(),
                  getParentForChildren(),
                  isClean());
          metadata_ = null;
        }
        return metadataBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:cosmos.base.snapshots.v1beta1.Snapshot)
    }

    // @@protoc_insertion_point(class_scope:cosmos.base.snapshots.v1beta1.Snapshot)
    private static final cosmos.base.snapshots.v1beta1.SnapshotOuterClass.Snapshot DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cosmos.base.snapshots.v1beta1.SnapshotOuterClass.Snapshot();
    }

    public static cosmos.base.snapshots.v1beta1.SnapshotOuterClass.Snapshot getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Snapshot>
        PARSER = new com.google.protobuf.AbstractParser<Snapshot>() {
      public Snapshot parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Snapshot(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Snapshot> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Snapshot> getParserForType() {
      return PARSER;
    }

    public cosmos.base.snapshots.v1beta1.SnapshotOuterClass.Snapshot getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MetadataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cosmos.base.snapshots.v1beta1.Metadata)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * SHA-256 chunk hashes
     * </pre>
     *
     * <code>repeated bytes chunk_hashes = 1;</code>
     */
    java.util.List<com.google.protobuf.ByteString> getChunkHashesList();
    /**
     * <pre>
     * SHA-256 chunk hashes
     * </pre>
     *
     * <code>repeated bytes chunk_hashes = 1;</code>
     */
    int getChunkHashesCount();
    /**
     * <pre>
     * SHA-256 chunk hashes
     * </pre>
     *
     * <code>repeated bytes chunk_hashes = 1;</code>
     */
    com.google.protobuf.ByteString getChunkHashes(int index);
  }
  /**
   * <pre>
   * Metadata contains SDK-specific snapshot metadata.
   * </pre>
   *
   * Protobuf type {@code cosmos.base.snapshots.v1beta1.Metadata}
   */
  public  static final class Metadata extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cosmos.base.snapshots.v1beta1.Metadata)
      MetadataOrBuilder {
    // Use Metadata.newBuilder() to construct.
    private Metadata(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Metadata() {
      chunkHashes_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Metadata(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                chunkHashes_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000001;
              }
              chunkHashes_.add(input.readBytes());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          chunkHashes_ = java.util.Collections.unmodifiableList(chunkHashes_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cosmos.base.snapshots.v1beta1.SnapshotOuterClass.internal_static_cosmos_base_snapshots_v1beta1_Metadata_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cosmos.base.snapshots.v1beta1.SnapshotOuterClass.internal_static_cosmos_base_snapshots_v1beta1_Metadata_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cosmos.base.snapshots.v1beta1.SnapshotOuterClass.Metadata.class, cosmos.base.snapshots.v1beta1.SnapshotOuterClass.Metadata.Builder.class);
    }

    public static final int CHUNK_HASHES_FIELD_NUMBER = 1;
    private java.util.List<com.google.protobuf.ByteString> chunkHashes_;
    /**
     * <pre>
     * SHA-256 chunk hashes
     * </pre>
     *
     * <code>repeated bytes chunk_hashes = 1;</code>
     */
    public java.util.List<com.google.protobuf.ByteString>
        getChunkHashesList() {
      return chunkHashes_;
    }
    /**
     * <pre>
     * SHA-256 chunk hashes
     * </pre>
     *
     * <code>repeated bytes chunk_hashes = 1;</code>
     */
    public int getChunkHashesCount() {
      return chunkHashes_.size();
    }
    /**
     * <pre>
     * SHA-256 chunk hashes
     * </pre>
     *
     * <code>repeated bytes chunk_hashes = 1;</code>
     */
    public com.google.protobuf.ByteString getChunkHashes(int index) {
      return chunkHashes_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < chunkHashes_.size(); i++) {
        output.writeBytes(1, chunkHashes_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < chunkHashes_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(chunkHashes_.get(i));
        }
        size += dataSize;
        size += 1 * getChunkHashesList().size();
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cosmos.base.snapshots.v1beta1.SnapshotOuterClass.Metadata)) {
        return super.equals(obj);
      }
      cosmos.base.snapshots.v1beta1.SnapshotOuterClass.Metadata other = (cosmos.base.snapshots.v1beta1.SnapshotOuterClass.Metadata) obj;

      boolean result = true;
      result = result && getChunkHashesList()
          .equals(other.getChunkHashesList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getChunkHashesCount() > 0) {
        hash = (37 * hash) + CHUNK_HASHES_FIELD_NUMBER;
        hash = (53 * hash) + getChunkHashesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cosmos.base.snapshots.v1beta1.SnapshotOuterClass.Metadata parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cosmos.base.snapshots.v1beta1.SnapshotOuterClass.Metadata parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cosmos.base.snapshots.v1beta1.SnapshotOuterClass.Metadata parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cosmos.base.snapshots.v1beta1.SnapshotOuterClass.Metadata parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cosmos.base.snapshots.v1beta1.SnapshotOuterClass.Metadata parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cosmos.base.snapshots.v1beta1.SnapshotOuterClass.Metadata parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cosmos.base.snapshots.v1beta1.SnapshotOuterClass.Metadata parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cosmos.base.snapshots.v1beta1.SnapshotOuterClass.Metadata parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cosmos.base.snapshots.v1beta1.SnapshotOuterClass.Metadata parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cosmos.base.snapshots.v1beta1.SnapshotOuterClass.Metadata parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cosmos.base.snapshots.v1beta1.SnapshotOuterClass.Metadata prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Metadata contains SDK-specific snapshot metadata.
     * </pre>
     *
     * Protobuf type {@code cosmos.base.snapshots.v1beta1.Metadata}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cosmos.base.snapshots.v1beta1.Metadata)
        cosmos.base.snapshots.v1beta1.SnapshotOuterClass.MetadataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cosmos.base.snapshots.v1beta1.SnapshotOuterClass.internal_static_cosmos_base_snapshots_v1beta1_Metadata_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cosmos.base.snapshots.v1beta1.SnapshotOuterClass.internal_static_cosmos_base_snapshots_v1beta1_Metadata_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cosmos.base.snapshots.v1beta1.SnapshotOuterClass.Metadata.class, cosmos.base.snapshots.v1beta1.SnapshotOuterClass.Metadata.Builder.class);
      }

      // Construct using cosmos.base.snapshots.v1beta1.SnapshotOuterClass.Metadata.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        chunkHashes_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cosmos.base.snapshots.v1beta1.SnapshotOuterClass.internal_static_cosmos_base_snapshots_v1beta1_Metadata_descriptor;
      }

      public cosmos.base.snapshots.v1beta1.SnapshotOuterClass.Metadata getDefaultInstanceForType() {
        return cosmos.base.snapshots.v1beta1.SnapshotOuterClass.Metadata.getDefaultInstance();
      }

      public cosmos.base.snapshots.v1beta1.SnapshotOuterClass.Metadata build() {
        cosmos.base.snapshots.v1beta1.SnapshotOuterClass.Metadata result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cosmos.base.snapshots.v1beta1.SnapshotOuterClass.Metadata buildPartial() {
        cosmos.base.snapshots.v1beta1.SnapshotOuterClass.Metadata result = new cosmos.base.snapshots.v1beta1.SnapshotOuterClass.Metadata(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          chunkHashes_ = java.util.Collections.unmodifiableList(chunkHashes_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.chunkHashes_ = chunkHashes_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cosmos.base.snapshots.v1beta1.SnapshotOuterClass.Metadata) {
          return mergeFrom((cosmos.base.snapshots.v1beta1.SnapshotOuterClass.Metadata)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cosmos.base.snapshots.v1beta1.SnapshotOuterClass.Metadata other) {
        if (other == cosmos.base.snapshots.v1beta1.SnapshotOuterClass.Metadata.getDefaultInstance()) return this;
        if (!other.chunkHashes_.isEmpty()) {
          if (chunkHashes_.isEmpty()) {
            chunkHashes_ = other.chunkHashes_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureChunkHashesIsMutable();
            chunkHashes_.addAll(other.chunkHashes_);
          }
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cosmos.base.snapshots.v1beta1.SnapshotOuterClass.Metadata parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cosmos.base.snapshots.v1beta1.SnapshotOuterClass.Metadata) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.google.protobuf.ByteString> chunkHashes_ = java.util.Collections.emptyList();
      private void ensureChunkHashesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          chunkHashes_ = new java.util.ArrayList<com.google.protobuf.ByteString>(chunkHashes_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <pre>
       * SHA-256 chunk hashes
       * </pre>
       *
       * <code>repeated bytes chunk_hashes = 1;</code>
       */
      public java.util.List<com.google.protobuf.ByteString>
          getChunkHashesList() {
        return java.util.Collections.unmodifiableList(chunkHashes_);
      }
      /**
       * <pre>
       * SHA-256 chunk hashes
       * </pre>
       *
       * <code>repeated bytes chunk_hashes = 1;</code>
       */
      public int getChunkHashesCount() {
        return chunkHashes_.size();
      }
      /**
       * <pre>
       * SHA-256 chunk hashes
       * </pre>
       *
       * <code>repeated bytes chunk_hashes = 1;</code>
       */
      public com.google.protobuf.ByteString getChunkHashes(int index) {
        return chunkHashes_.get(index);
      }
      /**
       * <pre>
       * SHA-256 chunk hashes
       * </pre>
       *
       * <code>repeated bytes chunk_hashes = 1;</code>
       */
      public Builder setChunkHashes(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureChunkHashesIsMutable();
        chunkHashes_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * SHA-256 chunk hashes
       * </pre>
       *
       * <code>repeated bytes chunk_hashes = 1;</code>
       */
      public Builder addChunkHashes(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureChunkHashesIsMutable();
        chunkHashes_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * SHA-256 chunk hashes
       * </pre>
       *
       * <code>repeated bytes chunk_hashes = 1;</code>
       */
      public Builder addAllChunkHashes(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureChunkHashesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, chunkHashes_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * SHA-256 chunk hashes
       * </pre>
       *
       * <code>repeated bytes chunk_hashes = 1;</code>
       */
      public Builder clearChunkHashes() {
        chunkHashes_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:cosmos.base.snapshots.v1beta1.Metadata)
    }

    // @@protoc_insertion_point(class_scope:cosmos.base.snapshots.v1beta1.Metadata)
    private static final cosmos.base.snapshots.v1beta1.SnapshotOuterClass.Metadata DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cosmos.base.snapshots.v1beta1.SnapshotOuterClass.Metadata();
    }

    public static cosmos.base.snapshots.v1beta1.SnapshotOuterClass.Metadata getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Metadata>
        PARSER = new com.google.protobuf.AbstractParser<Metadata>() {
      public Metadata parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Metadata(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Metadata> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Metadata> getParserForType() {
      return PARSER;
    }

    public cosmos.base.snapshots.v1beta1.SnapshotOuterClass.Metadata getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cosmos_base_snapshots_v1beta1_Snapshot_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cosmos_base_snapshots_v1beta1_Snapshot_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cosmos_base_snapshots_v1beta1_Metadata_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cosmos_base_snapshots_v1beta1_Metadata_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n,cosmos/base/snapshots/v1beta1/snapshot" +
      ".proto\022\035cosmos.base.snapshots.v1beta1\032\024g" +
      "ogoproto/gogo.proto\"\211\001\n\010Snapshot\022\016\n\006heig" +
      "ht\030\001 \001(\004\022\016\n\006format\030\002 \001(\r\022\016\n\006chunks\030\003 \001(\r" +
      "\022\014\n\004hash\030\004 \001(\014\022?\n\010metadata\030\005 \001(\0132\'.cosmo" +
      "s.base.snapshots.v1beta1.MetadataB\004\310\336\037\000\"" +
      " \n\010Metadata\022\024\n\014chunk_hashes\030\001 \003(\014B.Z,git" +
      "hub.com/cosmos/cosmos-sdk/snapshots/type" +
      "sb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.GoGoProtos.getDescriptor(),
        }, assigner);
    internal_static_cosmos_base_snapshots_v1beta1_Snapshot_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cosmos_base_snapshots_v1beta1_Snapshot_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cosmos_base_snapshots_v1beta1_Snapshot_descriptor,
        new java.lang.String[] { "Height", "Format", "Chunks", "Hash", "Metadata", });
    internal_static_cosmos_base_snapshots_v1beta1_Metadata_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_cosmos_base_snapshots_v1beta1_Metadata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cosmos_base_snapshots_v1beta1_Metadata_descriptor,
        new java.lang.String[] { "ChunkHashes", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.protobuf.GoGoProtos.nullable);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.protobuf.GoGoProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
