// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cosmos/auth/v1beta1/auth.proto

package cosmos.auth.v1beta1;

public final class Auth {
  private Auth() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BaseAccountOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cosmos.auth.v1beta1.BaseAccount)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string address = 1;</code>
     */
    java.lang.String getAddress();
    /**
     * <code>optional string address = 1;</code>
     */
    com.google.protobuf.ByteString
        getAddressBytes();

    /**
     * <code>optional .google.protobuf.Any pub_key = 2;</code>
     */
    boolean hasPubKey();
    /**
     * <code>optional .google.protobuf.Any pub_key = 2;</code>
     */
    com.google.protobuf.Any getPubKey();
    /**
     * <code>optional .google.protobuf.Any pub_key = 2;</code>
     */
    com.google.protobuf.AnyOrBuilder getPubKeyOrBuilder();

    /**
     * <code>optional uint64 account_number = 3;</code>
     */
    long getAccountNumber();

    /**
     * <code>optional uint64 sequence = 4;</code>
     */
    long getSequence();
  }
  /**
   * <pre>
   * BaseAccount defines a base account type. It contains all the necessary fields
   * for basic account functionality. Any custom account type should extend this
   * type for additional functionality (e.g. vesting).
   * </pre>
   *
   * Protobuf type {@code cosmos.auth.v1beta1.BaseAccount}
   */
  public  static final class BaseAccount extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cosmos.auth.v1beta1.BaseAccount)
      BaseAccountOrBuilder {
    // Use BaseAccount.newBuilder() to construct.
    private BaseAccount(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BaseAccount() {
      address_ = "";
      accountNumber_ = 0L;
      sequence_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private BaseAccount(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              address_ = s;
              break;
            }
            case 18: {
              com.google.protobuf.Any.Builder subBuilder = null;
              if (pubKey_ != null) {
                subBuilder = pubKey_.toBuilder();
              }
              pubKey_ = input.readMessage(com.google.protobuf.Any.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(pubKey_);
                pubKey_ = subBuilder.buildPartial();
              }

              break;
            }
            case 24: {

              accountNumber_ = input.readUInt64();
              break;
            }
            case 32: {

              sequence_ = input.readUInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cosmos.auth.v1beta1.Auth.internal_static_cosmos_auth_v1beta1_BaseAccount_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cosmos.auth.v1beta1.Auth.internal_static_cosmos_auth_v1beta1_BaseAccount_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cosmos.auth.v1beta1.Auth.BaseAccount.class, cosmos.auth.v1beta1.Auth.BaseAccount.Builder.class);
    }

    public static final int ADDRESS_FIELD_NUMBER = 1;
    private volatile java.lang.Object address_;
    /**
     * <code>optional string address = 1;</code>
     */
    public java.lang.String getAddress() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        address_ = s;
        return s;
      }
    }
    /**
     * <code>optional string address = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAddressBytes() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PUB_KEY_FIELD_NUMBER = 2;
    private com.google.protobuf.Any pubKey_;
    /**
     * <code>optional .google.protobuf.Any pub_key = 2;</code>
     */
    public boolean hasPubKey() {
      return pubKey_ != null;
    }
    /**
     * <code>optional .google.protobuf.Any pub_key = 2;</code>
     */
    public com.google.protobuf.Any getPubKey() {
      return pubKey_ == null ? com.google.protobuf.Any.getDefaultInstance() : pubKey_;
    }
    /**
     * <code>optional .google.protobuf.Any pub_key = 2;</code>
     */
    public com.google.protobuf.AnyOrBuilder getPubKeyOrBuilder() {
      return getPubKey();
    }

    public static final int ACCOUNT_NUMBER_FIELD_NUMBER = 3;
    private long accountNumber_;
    /**
     * <code>optional uint64 account_number = 3;</code>
     */
    public long getAccountNumber() {
      return accountNumber_;
    }

    public static final int SEQUENCE_FIELD_NUMBER = 4;
    private long sequence_;
    /**
     * <code>optional uint64 sequence = 4;</code>
     */
    public long getSequence() {
      return sequence_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getAddressBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, address_);
      }
      if (pubKey_ != null) {
        output.writeMessage(2, getPubKey());
      }
      if (accountNumber_ != 0L) {
        output.writeUInt64(3, accountNumber_);
      }
      if (sequence_ != 0L) {
        output.writeUInt64(4, sequence_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getAddressBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, address_);
      }
      if (pubKey_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getPubKey());
      }
      if (accountNumber_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, accountNumber_);
      }
      if (sequence_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(4, sequence_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cosmos.auth.v1beta1.Auth.BaseAccount)) {
        return super.equals(obj);
      }
      cosmos.auth.v1beta1.Auth.BaseAccount other = (cosmos.auth.v1beta1.Auth.BaseAccount) obj;

      boolean result = true;
      result = result && getAddress()
          .equals(other.getAddress());
      result = result && (hasPubKey() == other.hasPubKey());
      if (hasPubKey()) {
        result = result && getPubKey()
            .equals(other.getPubKey());
      }
      result = result && (getAccountNumber()
          == other.getAccountNumber());
      result = result && (getSequence()
          == other.getSequence());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddress().hashCode();
      if (hasPubKey()) {
        hash = (37 * hash) + PUB_KEY_FIELD_NUMBER;
        hash = (53 * hash) + getPubKey().hashCode();
      }
      hash = (37 * hash) + ACCOUNT_NUMBER_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getAccountNumber());
      hash = (37 * hash) + SEQUENCE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSequence());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cosmos.auth.v1beta1.Auth.BaseAccount parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cosmos.auth.v1beta1.Auth.BaseAccount parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cosmos.auth.v1beta1.Auth.BaseAccount parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cosmos.auth.v1beta1.Auth.BaseAccount parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cosmos.auth.v1beta1.Auth.BaseAccount parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cosmos.auth.v1beta1.Auth.BaseAccount parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cosmos.auth.v1beta1.Auth.BaseAccount parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cosmos.auth.v1beta1.Auth.BaseAccount parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cosmos.auth.v1beta1.Auth.BaseAccount parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cosmos.auth.v1beta1.Auth.BaseAccount parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cosmos.auth.v1beta1.Auth.BaseAccount prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * BaseAccount defines a base account type. It contains all the necessary fields
     * for basic account functionality. Any custom account type should extend this
     * type for additional functionality (e.g. vesting).
     * </pre>
     *
     * Protobuf type {@code cosmos.auth.v1beta1.BaseAccount}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cosmos.auth.v1beta1.BaseAccount)
        cosmos.auth.v1beta1.Auth.BaseAccountOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cosmos.auth.v1beta1.Auth.internal_static_cosmos_auth_v1beta1_BaseAccount_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cosmos.auth.v1beta1.Auth.internal_static_cosmos_auth_v1beta1_BaseAccount_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cosmos.auth.v1beta1.Auth.BaseAccount.class, cosmos.auth.v1beta1.Auth.BaseAccount.Builder.class);
      }

      // Construct using cosmos.auth.v1beta1.Auth.BaseAccount.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        address_ = "";

        if (pubKeyBuilder_ == null) {
          pubKey_ = null;
        } else {
          pubKey_ = null;
          pubKeyBuilder_ = null;
        }
        accountNumber_ = 0L;

        sequence_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cosmos.auth.v1beta1.Auth.internal_static_cosmos_auth_v1beta1_BaseAccount_descriptor;
      }

      public cosmos.auth.v1beta1.Auth.BaseAccount getDefaultInstanceForType() {
        return cosmos.auth.v1beta1.Auth.BaseAccount.getDefaultInstance();
      }

      public cosmos.auth.v1beta1.Auth.BaseAccount build() {
        cosmos.auth.v1beta1.Auth.BaseAccount result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cosmos.auth.v1beta1.Auth.BaseAccount buildPartial() {
        cosmos.auth.v1beta1.Auth.BaseAccount result = new cosmos.auth.v1beta1.Auth.BaseAccount(this);
        result.address_ = address_;
        if (pubKeyBuilder_ == null) {
          result.pubKey_ = pubKey_;
        } else {
          result.pubKey_ = pubKeyBuilder_.build();
        }
        result.accountNumber_ = accountNumber_;
        result.sequence_ = sequence_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cosmos.auth.v1beta1.Auth.BaseAccount) {
          return mergeFrom((cosmos.auth.v1beta1.Auth.BaseAccount)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cosmos.auth.v1beta1.Auth.BaseAccount other) {
        if (other == cosmos.auth.v1beta1.Auth.BaseAccount.getDefaultInstance()) return this;
        if (!other.getAddress().isEmpty()) {
          address_ = other.address_;
          onChanged();
        }
        if (other.hasPubKey()) {
          mergePubKey(other.getPubKey());
        }
        if (other.getAccountNumber() != 0L) {
          setAccountNumber(other.getAccountNumber());
        }
        if (other.getSequence() != 0L) {
          setSequence(other.getSequence());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cosmos.auth.v1beta1.Auth.BaseAccount parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cosmos.auth.v1beta1.Auth.BaseAccount) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object address_ = "";
      /**
       * <code>optional string address = 1;</code>
       */
      public java.lang.String getAddress() {
        java.lang.Object ref = address_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          address_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string address = 1;</code>
       */
      public com.google.protobuf.ByteString
          getAddressBytes() {
        java.lang.Object ref = address_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          address_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string address = 1;</code>
       */
      public Builder setAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        address_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string address = 1;</code>
       */
      public Builder clearAddress() {
        
        address_ = getDefaultInstance().getAddress();
        onChanged();
        return this;
      }
      /**
       * <code>optional string address = 1;</code>
       */
      public Builder setAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        address_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.Any pubKey_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> pubKeyBuilder_;
      /**
       * <code>optional .google.protobuf.Any pub_key = 2;</code>
       */
      public boolean hasPubKey() {
        return pubKeyBuilder_ != null || pubKey_ != null;
      }
      /**
       * <code>optional .google.protobuf.Any pub_key = 2;</code>
       */
      public com.google.protobuf.Any getPubKey() {
        if (pubKeyBuilder_ == null) {
          return pubKey_ == null ? com.google.protobuf.Any.getDefaultInstance() : pubKey_;
        } else {
          return pubKeyBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .google.protobuf.Any pub_key = 2;</code>
       */
      public Builder setPubKey(com.google.protobuf.Any value) {
        if (pubKeyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          pubKey_ = value;
          onChanged();
        } else {
          pubKeyBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .google.protobuf.Any pub_key = 2;</code>
       */
      public Builder setPubKey(
          com.google.protobuf.Any.Builder builderForValue) {
        if (pubKeyBuilder_ == null) {
          pubKey_ = builderForValue.build();
          onChanged();
        } else {
          pubKeyBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .google.protobuf.Any pub_key = 2;</code>
       */
      public Builder mergePubKey(com.google.protobuf.Any value) {
        if (pubKeyBuilder_ == null) {
          if (pubKey_ != null) {
            pubKey_ =
              com.google.protobuf.Any.newBuilder(pubKey_).mergeFrom(value).buildPartial();
          } else {
            pubKey_ = value;
          }
          onChanged();
        } else {
          pubKeyBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .google.protobuf.Any pub_key = 2;</code>
       */
      public Builder clearPubKey() {
        if (pubKeyBuilder_ == null) {
          pubKey_ = null;
          onChanged();
        } else {
          pubKey_ = null;
          pubKeyBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .google.protobuf.Any pub_key = 2;</code>
       */
      public com.google.protobuf.Any.Builder getPubKeyBuilder() {
        
        onChanged();
        return getPubKeyFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .google.protobuf.Any pub_key = 2;</code>
       */
      public com.google.protobuf.AnyOrBuilder getPubKeyOrBuilder() {
        if (pubKeyBuilder_ != null) {
          return pubKeyBuilder_.getMessageOrBuilder();
        } else {
          return pubKey_ == null ?
              com.google.protobuf.Any.getDefaultInstance() : pubKey_;
        }
      }
      /**
       * <code>optional .google.protobuf.Any pub_key = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
          getPubKeyFieldBuilder() {
        if (pubKeyBuilder_ == null) {
          pubKeyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                  getPubKey(),
                  getParentForChildren(),
                  isClean());
          pubKey_ = null;
        }
        return pubKeyBuilder_;
      }

      private long accountNumber_ ;
      /**
       * <code>optional uint64 account_number = 3;</code>
       */
      public long getAccountNumber() {
        return accountNumber_;
      }
      /**
       * <code>optional uint64 account_number = 3;</code>
       */
      public Builder setAccountNumber(long value) {
        
        accountNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 account_number = 3;</code>
       */
      public Builder clearAccountNumber() {
        
        accountNumber_ = 0L;
        onChanged();
        return this;
      }

      private long sequence_ ;
      /**
       * <code>optional uint64 sequence = 4;</code>
       */
      public long getSequence() {
        return sequence_;
      }
      /**
       * <code>optional uint64 sequence = 4;</code>
       */
      public Builder setSequence(long value) {
        
        sequence_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 sequence = 4;</code>
       */
      public Builder clearSequence() {
        
        sequence_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:cosmos.auth.v1beta1.BaseAccount)
    }

    // @@protoc_insertion_point(class_scope:cosmos.auth.v1beta1.BaseAccount)
    private static final cosmos.auth.v1beta1.Auth.BaseAccount DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cosmos.auth.v1beta1.Auth.BaseAccount();
    }

    public static cosmos.auth.v1beta1.Auth.BaseAccount getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BaseAccount>
        PARSER = new com.google.protobuf.AbstractParser<BaseAccount>() {
      public BaseAccount parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new BaseAccount(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BaseAccount> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BaseAccount> getParserForType() {
      return PARSER;
    }

    public cosmos.auth.v1beta1.Auth.BaseAccount getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ModuleAccountOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cosmos.auth.v1beta1.ModuleAccount)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .cosmos.auth.v1beta1.BaseAccount base_account = 1;</code>
     */
    boolean hasBaseAccount();
    /**
     * <code>optional .cosmos.auth.v1beta1.BaseAccount base_account = 1;</code>
     */
    cosmos.auth.v1beta1.Auth.BaseAccount getBaseAccount();
    /**
     * <code>optional .cosmos.auth.v1beta1.BaseAccount base_account = 1;</code>
     */
    cosmos.auth.v1beta1.Auth.BaseAccountOrBuilder getBaseAccountOrBuilder();

    /**
     * <code>optional string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>repeated string permissions = 3;</code>
     */
    java.util.List<java.lang.String>
        getPermissionsList();
    /**
     * <code>repeated string permissions = 3;</code>
     */
    int getPermissionsCount();
    /**
     * <code>repeated string permissions = 3;</code>
     */
    java.lang.String getPermissions(int index);
    /**
     * <code>repeated string permissions = 3;</code>
     */
    com.google.protobuf.ByteString
        getPermissionsBytes(int index);
  }
  /**
   * <pre>
   * ModuleAccount defines an account for modules that holds coins on a pool.
   * </pre>
   *
   * Protobuf type {@code cosmos.auth.v1beta1.ModuleAccount}
   */
  public  static final class ModuleAccount extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cosmos.auth.v1beta1.ModuleAccount)
      ModuleAccountOrBuilder {
    // Use ModuleAccount.newBuilder() to construct.
    private ModuleAccount(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ModuleAccount() {
      name_ = "";
      permissions_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ModuleAccount(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              cosmos.auth.v1beta1.Auth.BaseAccount.Builder subBuilder = null;
              if (baseAccount_ != null) {
                subBuilder = baseAccount_.toBuilder();
              }
              baseAccount_ = input.readMessage(cosmos.auth.v1beta1.Auth.BaseAccount.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(baseAccount_);
                baseAccount_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                permissions_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              permissions_.add(s);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          permissions_ = permissions_.getUnmodifiableView();
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cosmos.auth.v1beta1.Auth.internal_static_cosmos_auth_v1beta1_ModuleAccount_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cosmos.auth.v1beta1.Auth.internal_static_cosmos_auth_v1beta1_ModuleAccount_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cosmos.auth.v1beta1.Auth.ModuleAccount.class, cosmos.auth.v1beta1.Auth.ModuleAccount.Builder.class);
    }

    private int bitField0_;
    public static final int BASE_ACCOUNT_FIELD_NUMBER = 1;
    private cosmos.auth.v1beta1.Auth.BaseAccount baseAccount_;
    /**
     * <code>optional .cosmos.auth.v1beta1.BaseAccount base_account = 1;</code>
     */
    public boolean hasBaseAccount() {
      return baseAccount_ != null;
    }
    /**
     * <code>optional .cosmos.auth.v1beta1.BaseAccount base_account = 1;</code>
     */
    public cosmos.auth.v1beta1.Auth.BaseAccount getBaseAccount() {
      return baseAccount_ == null ? cosmos.auth.v1beta1.Auth.BaseAccount.getDefaultInstance() : baseAccount_;
    }
    /**
     * <code>optional .cosmos.auth.v1beta1.BaseAccount base_account = 1;</code>
     */
    public cosmos.auth.v1beta1.Auth.BaseAccountOrBuilder getBaseAccountOrBuilder() {
      return getBaseAccount();
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>optional string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PERMISSIONS_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList permissions_;
    /**
     * <code>repeated string permissions = 3;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getPermissionsList() {
      return permissions_;
    }
    /**
     * <code>repeated string permissions = 3;</code>
     */
    public int getPermissionsCount() {
      return permissions_.size();
    }
    /**
     * <code>repeated string permissions = 3;</code>
     */
    public java.lang.String getPermissions(int index) {
      return permissions_.get(index);
    }
    /**
     * <code>repeated string permissions = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPermissionsBytes(int index) {
      return permissions_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (baseAccount_ != null) {
        output.writeMessage(1, getBaseAccount());
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      for (int i = 0; i < permissions_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, permissions_.getRaw(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (baseAccount_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getBaseAccount());
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < permissions_.size(); i++) {
          dataSize += computeStringSizeNoTag(permissions_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getPermissionsList().size();
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cosmos.auth.v1beta1.Auth.ModuleAccount)) {
        return super.equals(obj);
      }
      cosmos.auth.v1beta1.Auth.ModuleAccount other = (cosmos.auth.v1beta1.Auth.ModuleAccount) obj;

      boolean result = true;
      result = result && (hasBaseAccount() == other.hasBaseAccount());
      if (hasBaseAccount()) {
        result = result && getBaseAccount()
            .equals(other.getBaseAccount());
      }
      result = result && getName()
          .equals(other.getName());
      result = result && getPermissionsList()
          .equals(other.getPermissionsList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasBaseAccount()) {
        hash = (37 * hash) + BASE_ACCOUNT_FIELD_NUMBER;
        hash = (53 * hash) + getBaseAccount().hashCode();
      }
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      if (getPermissionsCount() > 0) {
        hash = (37 * hash) + PERMISSIONS_FIELD_NUMBER;
        hash = (53 * hash) + getPermissionsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cosmos.auth.v1beta1.Auth.ModuleAccount parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cosmos.auth.v1beta1.Auth.ModuleAccount parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cosmos.auth.v1beta1.Auth.ModuleAccount parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cosmos.auth.v1beta1.Auth.ModuleAccount parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cosmos.auth.v1beta1.Auth.ModuleAccount parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cosmos.auth.v1beta1.Auth.ModuleAccount parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cosmos.auth.v1beta1.Auth.ModuleAccount parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cosmos.auth.v1beta1.Auth.ModuleAccount parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cosmos.auth.v1beta1.Auth.ModuleAccount parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cosmos.auth.v1beta1.Auth.ModuleAccount parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cosmos.auth.v1beta1.Auth.ModuleAccount prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * ModuleAccount defines an account for modules that holds coins on a pool.
     * </pre>
     *
     * Protobuf type {@code cosmos.auth.v1beta1.ModuleAccount}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cosmos.auth.v1beta1.ModuleAccount)
        cosmos.auth.v1beta1.Auth.ModuleAccountOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cosmos.auth.v1beta1.Auth.internal_static_cosmos_auth_v1beta1_ModuleAccount_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cosmos.auth.v1beta1.Auth.internal_static_cosmos_auth_v1beta1_ModuleAccount_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cosmos.auth.v1beta1.Auth.ModuleAccount.class, cosmos.auth.v1beta1.Auth.ModuleAccount.Builder.class);
      }

      // Construct using cosmos.auth.v1beta1.Auth.ModuleAccount.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (baseAccountBuilder_ == null) {
          baseAccount_ = null;
        } else {
          baseAccount_ = null;
          baseAccountBuilder_ = null;
        }
        name_ = "";

        permissions_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cosmos.auth.v1beta1.Auth.internal_static_cosmos_auth_v1beta1_ModuleAccount_descriptor;
      }

      public cosmos.auth.v1beta1.Auth.ModuleAccount getDefaultInstanceForType() {
        return cosmos.auth.v1beta1.Auth.ModuleAccount.getDefaultInstance();
      }

      public cosmos.auth.v1beta1.Auth.ModuleAccount build() {
        cosmos.auth.v1beta1.Auth.ModuleAccount result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cosmos.auth.v1beta1.Auth.ModuleAccount buildPartial() {
        cosmos.auth.v1beta1.Auth.ModuleAccount result = new cosmos.auth.v1beta1.Auth.ModuleAccount(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (baseAccountBuilder_ == null) {
          result.baseAccount_ = baseAccount_;
        } else {
          result.baseAccount_ = baseAccountBuilder_.build();
        }
        result.name_ = name_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          permissions_ = permissions_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.permissions_ = permissions_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cosmos.auth.v1beta1.Auth.ModuleAccount) {
          return mergeFrom((cosmos.auth.v1beta1.Auth.ModuleAccount)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cosmos.auth.v1beta1.Auth.ModuleAccount other) {
        if (other == cosmos.auth.v1beta1.Auth.ModuleAccount.getDefaultInstance()) return this;
        if (other.hasBaseAccount()) {
          mergeBaseAccount(other.getBaseAccount());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.permissions_.isEmpty()) {
          if (permissions_.isEmpty()) {
            permissions_ = other.permissions_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensurePermissionsIsMutable();
            permissions_.addAll(other.permissions_);
          }
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cosmos.auth.v1beta1.Auth.ModuleAccount parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cosmos.auth.v1beta1.Auth.ModuleAccount) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private cosmos.auth.v1beta1.Auth.BaseAccount baseAccount_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          cosmos.auth.v1beta1.Auth.BaseAccount, cosmos.auth.v1beta1.Auth.BaseAccount.Builder, cosmos.auth.v1beta1.Auth.BaseAccountOrBuilder> baseAccountBuilder_;
      /**
       * <code>optional .cosmos.auth.v1beta1.BaseAccount base_account = 1;</code>
       */
      public boolean hasBaseAccount() {
        return baseAccountBuilder_ != null || baseAccount_ != null;
      }
      /**
       * <code>optional .cosmos.auth.v1beta1.BaseAccount base_account = 1;</code>
       */
      public cosmos.auth.v1beta1.Auth.BaseAccount getBaseAccount() {
        if (baseAccountBuilder_ == null) {
          return baseAccount_ == null ? cosmos.auth.v1beta1.Auth.BaseAccount.getDefaultInstance() : baseAccount_;
        } else {
          return baseAccountBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .cosmos.auth.v1beta1.BaseAccount base_account = 1;</code>
       */
      public Builder setBaseAccount(cosmos.auth.v1beta1.Auth.BaseAccount value) {
        if (baseAccountBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          baseAccount_ = value;
          onChanged();
        } else {
          baseAccountBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .cosmos.auth.v1beta1.BaseAccount base_account = 1;</code>
       */
      public Builder setBaseAccount(
          cosmos.auth.v1beta1.Auth.BaseAccount.Builder builderForValue) {
        if (baseAccountBuilder_ == null) {
          baseAccount_ = builderForValue.build();
          onChanged();
        } else {
          baseAccountBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .cosmos.auth.v1beta1.BaseAccount base_account = 1;</code>
       */
      public Builder mergeBaseAccount(cosmos.auth.v1beta1.Auth.BaseAccount value) {
        if (baseAccountBuilder_ == null) {
          if (baseAccount_ != null) {
            baseAccount_ =
              cosmos.auth.v1beta1.Auth.BaseAccount.newBuilder(baseAccount_).mergeFrom(value).buildPartial();
          } else {
            baseAccount_ = value;
          }
          onChanged();
        } else {
          baseAccountBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .cosmos.auth.v1beta1.BaseAccount base_account = 1;</code>
       */
      public Builder clearBaseAccount() {
        if (baseAccountBuilder_ == null) {
          baseAccount_ = null;
          onChanged();
        } else {
          baseAccount_ = null;
          baseAccountBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .cosmos.auth.v1beta1.BaseAccount base_account = 1;</code>
       */
      public cosmos.auth.v1beta1.Auth.BaseAccount.Builder getBaseAccountBuilder() {
        
        onChanged();
        return getBaseAccountFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .cosmos.auth.v1beta1.BaseAccount base_account = 1;</code>
       */
      public cosmos.auth.v1beta1.Auth.BaseAccountOrBuilder getBaseAccountOrBuilder() {
        if (baseAccountBuilder_ != null) {
          return baseAccountBuilder_.getMessageOrBuilder();
        } else {
          return baseAccount_ == null ?
              cosmos.auth.v1beta1.Auth.BaseAccount.getDefaultInstance() : baseAccount_;
        }
      }
      /**
       * <code>optional .cosmos.auth.v1beta1.BaseAccount base_account = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          cosmos.auth.v1beta1.Auth.BaseAccount, cosmos.auth.v1beta1.Auth.BaseAccount.Builder, cosmos.auth.v1beta1.Auth.BaseAccountOrBuilder> 
          getBaseAccountFieldBuilder() {
        if (baseAccountBuilder_ == null) {
          baseAccountBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              cosmos.auth.v1beta1.Auth.BaseAccount, cosmos.auth.v1beta1.Auth.BaseAccount.Builder, cosmos.auth.v1beta1.Auth.BaseAccountOrBuilder>(
                  getBaseAccount(),
                  getParentForChildren(),
                  isClean());
          baseAccount_ = null;
        }
        return baseAccountBuilder_;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList permissions_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensurePermissionsIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          permissions_ = new com.google.protobuf.LazyStringArrayList(permissions_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated string permissions = 3;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getPermissionsList() {
        return permissions_.getUnmodifiableView();
      }
      /**
       * <code>repeated string permissions = 3;</code>
       */
      public int getPermissionsCount() {
        return permissions_.size();
      }
      /**
       * <code>repeated string permissions = 3;</code>
       */
      public java.lang.String getPermissions(int index) {
        return permissions_.get(index);
      }
      /**
       * <code>repeated string permissions = 3;</code>
       */
      public com.google.protobuf.ByteString
          getPermissionsBytes(int index) {
        return permissions_.getByteString(index);
      }
      /**
       * <code>repeated string permissions = 3;</code>
       */
      public Builder setPermissions(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePermissionsIsMutable();
        permissions_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string permissions = 3;</code>
       */
      public Builder addPermissions(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePermissionsIsMutable();
        permissions_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string permissions = 3;</code>
       */
      public Builder addAllPermissions(
          java.lang.Iterable<java.lang.String> values) {
        ensurePermissionsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, permissions_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string permissions = 3;</code>
       */
      public Builder clearPermissions() {
        permissions_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string permissions = 3;</code>
       */
      public Builder addPermissionsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensurePermissionsIsMutable();
        permissions_.add(value);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:cosmos.auth.v1beta1.ModuleAccount)
    }

    // @@protoc_insertion_point(class_scope:cosmos.auth.v1beta1.ModuleAccount)
    private static final cosmos.auth.v1beta1.Auth.ModuleAccount DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cosmos.auth.v1beta1.Auth.ModuleAccount();
    }

    public static cosmos.auth.v1beta1.Auth.ModuleAccount getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ModuleAccount>
        PARSER = new com.google.protobuf.AbstractParser<ModuleAccount>() {
      public ModuleAccount parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ModuleAccount(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ModuleAccount> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ModuleAccount> getParserForType() {
      return PARSER;
    }

    public cosmos.auth.v1beta1.Auth.ModuleAccount getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ParamsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cosmos.auth.v1beta1.Params)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional uint64 max_memo_characters = 1;</code>
     */
    long getMaxMemoCharacters();

    /**
     * <code>optional uint64 tx_sig_limit = 2;</code>
     */
    long getTxSigLimit();

    /**
     * <code>optional uint64 tx_size_cost_per_byte = 3;</code>
     */
    long getTxSizeCostPerByte();

    /**
     * <code>optional uint64 sig_verify_cost_ed25519 = 4;</code>
     */
    long getSigVerifyCostEd25519();

    /**
     * <code>optional uint64 sig_verify_cost_secp256k1 = 5;</code>
     */
    long getSigVerifyCostSecp256K1();

    /**
     * <code>optional uint64 sig_verify_cost_sm2 = 6;</code>
     */
    long getSigVerifyCostSm2();
  }
  /**
   * <pre>
   * Params defines the parameters for the auth module.
   * </pre>
   *
   * Protobuf type {@code cosmos.auth.v1beta1.Params}
   */
  public  static final class Params extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cosmos.auth.v1beta1.Params)
      ParamsOrBuilder {
    // Use Params.newBuilder() to construct.
    private Params(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Params() {
      maxMemoCharacters_ = 0L;
      txSigLimit_ = 0L;
      txSizeCostPerByte_ = 0L;
      sigVerifyCostEd25519_ = 0L;
      sigVerifyCostSecp256K1_ = 0L;
      sigVerifyCostSm2_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Params(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              maxMemoCharacters_ = input.readUInt64();
              break;
            }
            case 16: {

              txSigLimit_ = input.readUInt64();
              break;
            }
            case 24: {

              txSizeCostPerByte_ = input.readUInt64();
              break;
            }
            case 32: {

              sigVerifyCostEd25519_ = input.readUInt64();
              break;
            }
            case 40: {

              sigVerifyCostSecp256K1_ = input.readUInt64();
              break;
            }
            case 48: {

              sigVerifyCostSm2_ = input.readUInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cosmos.auth.v1beta1.Auth.internal_static_cosmos_auth_v1beta1_Params_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cosmos.auth.v1beta1.Auth.internal_static_cosmos_auth_v1beta1_Params_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cosmos.auth.v1beta1.Auth.Params.class, cosmos.auth.v1beta1.Auth.Params.Builder.class);
    }

    public static final int MAX_MEMO_CHARACTERS_FIELD_NUMBER = 1;
    private long maxMemoCharacters_;
    /**
     * <code>optional uint64 max_memo_characters = 1;</code>
     */
    public long getMaxMemoCharacters() {
      return maxMemoCharacters_;
    }

    public static final int TX_SIG_LIMIT_FIELD_NUMBER = 2;
    private long txSigLimit_;
    /**
     * <code>optional uint64 tx_sig_limit = 2;</code>
     */
    public long getTxSigLimit() {
      return txSigLimit_;
    }

    public static final int TX_SIZE_COST_PER_BYTE_FIELD_NUMBER = 3;
    private long txSizeCostPerByte_;
    /**
     * <code>optional uint64 tx_size_cost_per_byte = 3;</code>
     */
    public long getTxSizeCostPerByte() {
      return txSizeCostPerByte_;
    }

    public static final int SIG_VERIFY_COST_ED25519_FIELD_NUMBER = 4;
    private long sigVerifyCostEd25519_;
    /**
     * <code>optional uint64 sig_verify_cost_ed25519 = 4;</code>
     */
    public long getSigVerifyCostEd25519() {
      return sigVerifyCostEd25519_;
    }

    public static final int SIG_VERIFY_COST_SECP256K1_FIELD_NUMBER = 5;
    private long sigVerifyCostSecp256K1_;
    /**
     * <code>optional uint64 sig_verify_cost_secp256k1 = 5;</code>
     */
    public long getSigVerifyCostSecp256K1() {
      return sigVerifyCostSecp256K1_;
    }

    public static final int SIG_VERIFY_COST_SM2_FIELD_NUMBER = 6;
    private long sigVerifyCostSm2_;
    /**
     * <code>optional uint64 sig_verify_cost_sm2 = 6;</code>
     */
    public long getSigVerifyCostSm2() {
      return sigVerifyCostSm2_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (maxMemoCharacters_ != 0L) {
        output.writeUInt64(1, maxMemoCharacters_);
      }
      if (txSigLimit_ != 0L) {
        output.writeUInt64(2, txSigLimit_);
      }
      if (txSizeCostPerByte_ != 0L) {
        output.writeUInt64(3, txSizeCostPerByte_);
      }
      if (sigVerifyCostEd25519_ != 0L) {
        output.writeUInt64(4, sigVerifyCostEd25519_);
      }
      if (sigVerifyCostSecp256K1_ != 0L) {
        output.writeUInt64(5, sigVerifyCostSecp256K1_);
      }
      if (sigVerifyCostSm2_ != 0L) {
        output.writeUInt64(6, sigVerifyCostSm2_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (maxMemoCharacters_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, maxMemoCharacters_);
      }
      if (txSigLimit_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, txSigLimit_);
      }
      if (txSizeCostPerByte_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, txSizeCostPerByte_);
      }
      if (sigVerifyCostEd25519_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(4, sigVerifyCostEd25519_);
      }
      if (sigVerifyCostSecp256K1_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(5, sigVerifyCostSecp256K1_);
      }
      if (sigVerifyCostSm2_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(6, sigVerifyCostSm2_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cosmos.auth.v1beta1.Auth.Params)) {
        return super.equals(obj);
      }
      cosmos.auth.v1beta1.Auth.Params other = (cosmos.auth.v1beta1.Auth.Params) obj;

      boolean result = true;
      result = result && (getMaxMemoCharacters()
          == other.getMaxMemoCharacters());
      result = result && (getTxSigLimit()
          == other.getTxSigLimit());
      result = result && (getTxSizeCostPerByte()
          == other.getTxSizeCostPerByte());
      result = result && (getSigVerifyCostEd25519()
          == other.getSigVerifyCostEd25519());
      result = result && (getSigVerifyCostSecp256K1()
          == other.getSigVerifyCostSecp256K1());
      result = result && (getSigVerifyCostSm2()
          == other.getSigVerifyCostSm2());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + MAX_MEMO_CHARACTERS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMaxMemoCharacters());
      hash = (37 * hash) + TX_SIG_LIMIT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTxSigLimit());
      hash = (37 * hash) + TX_SIZE_COST_PER_BYTE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTxSizeCostPerByte());
      hash = (37 * hash) + SIG_VERIFY_COST_ED25519_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSigVerifyCostEd25519());
      hash = (37 * hash) + SIG_VERIFY_COST_SECP256K1_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSigVerifyCostSecp256K1());
      hash = (37 * hash) + SIG_VERIFY_COST_SM2_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSigVerifyCostSm2());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cosmos.auth.v1beta1.Auth.Params parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cosmos.auth.v1beta1.Auth.Params parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cosmos.auth.v1beta1.Auth.Params parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cosmos.auth.v1beta1.Auth.Params parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cosmos.auth.v1beta1.Auth.Params parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cosmos.auth.v1beta1.Auth.Params parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cosmos.auth.v1beta1.Auth.Params parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cosmos.auth.v1beta1.Auth.Params parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cosmos.auth.v1beta1.Auth.Params parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cosmos.auth.v1beta1.Auth.Params parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cosmos.auth.v1beta1.Auth.Params prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Params defines the parameters for the auth module.
     * </pre>
     *
     * Protobuf type {@code cosmos.auth.v1beta1.Params}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cosmos.auth.v1beta1.Params)
        cosmos.auth.v1beta1.Auth.ParamsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cosmos.auth.v1beta1.Auth.internal_static_cosmos_auth_v1beta1_Params_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cosmos.auth.v1beta1.Auth.internal_static_cosmos_auth_v1beta1_Params_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cosmos.auth.v1beta1.Auth.Params.class, cosmos.auth.v1beta1.Auth.Params.Builder.class);
      }

      // Construct using cosmos.auth.v1beta1.Auth.Params.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        maxMemoCharacters_ = 0L;

        txSigLimit_ = 0L;

        txSizeCostPerByte_ = 0L;

        sigVerifyCostEd25519_ = 0L;

        sigVerifyCostSecp256K1_ = 0L;

        sigVerifyCostSm2_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cosmos.auth.v1beta1.Auth.internal_static_cosmos_auth_v1beta1_Params_descriptor;
      }

      public cosmos.auth.v1beta1.Auth.Params getDefaultInstanceForType() {
        return cosmos.auth.v1beta1.Auth.Params.getDefaultInstance();
      }

      public cosmos.auth.v1beta1.Auth.Params build() {
        cosmos.auth.v1beta1.Auth.Params result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cosmos.auth.v1beta1.Auth.Params buildPartial() {
        cosmos.auth.v1beta1.Auth.Params result = new cosmos.auth.v1beta1.Auth.Params(this);
        result.maxMemoCharacters_ = maxMemoCharacters_;
        result.txSigLimit_ = txSigLimit_;
        result.txSizeCostPerByte_ = txSizeCostPerByte_;
        result.sigVerifyCostEd25519_ = sigVerifyCostEd25519_;
        result.sigVerifyCostSecp256K1_ = sigVerifyCostSecp256K1_;
        result.sigVerifyCostSm2_ = sigVerifyCostSm2_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cosmos.auth.v1beta1.Auth.Params) {
          return mergeFrom((cosmos.auth.v1beta1.Auth.Params)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cosmos.auth.v1beta1.Auth.Params other) {
        if (other == cosmos.auth.v1beta1.Auth.Params.getDefaultInstance()) return this;
        if (other.getMaxMemoCharacters() != 0L) {
          setMaxMemoCharacters(other.getMaxMemoCharacters());
        }
        if (other.getTxSigLimit() != 0L) {
          setTxSigLimit(other.getTxSigLimit());
        }
        if (other.getTxSizeCostPerByte() != 0L) {
          setTxSizeCostPerByte(other.getTxSizeCostPerByte());
        }
        if (other.getSigVerifyCostEd25519() != 0L) {
          setSigVerifyCostEd25519(other.getSigVerifyCostEd25519());
        }
        if (other.getSigVerifyCostSecp256K1() != 0L) {
          setSigVerifyCostSecp256K1(other.getSigVerifyCostSecp256K1());
        }
        if (other.getSigVerifyCostSm2() != 0L) {
          setSigVerifyCostSm2(other.getSigVerifyCostSm2());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cosmos.auth.v1beta1.Auth.Params parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cosmos.auth.v1beta1.Auth.Params) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long maxMemoCharacters_ ;
      /**
       * <code>optional uint64 max_memo_characters = 1;</code>
       */
      public long getMaxMemoCharacters() {
        return maxMemoCharacters_;
      }
      /**
       * <code>optional uint64 max_memo_characters = 1;</code>
       */
      public Builder setMaxMemoCharacters(long value) {
        
        maxMemoCharacters_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 max_memo_characters = 1;</code>
       */
      public Builder clearMaxMemoCharacters() {
        
        maxMemoCharacters_ = 0L;
        onChanged();
        return this;
      }

      private long txSigLimit_ ;
      /**
       * <code>optional uint64 tx_sig_limit = 2;</code>
       */
      public long getTxSigLimit() {
        return txSigLimit_;
      }
      /**
       * <code>optional uint64 tx_sig_limit = 2;</code>
       */
      public Builder setTxSigLimit(long value) {
        
        txSigLimit_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 tx_sig_limit = 2;</code>
       */
      public Builder clearTxSigLimit() {
        
        txSigLimit_ = 0L;
        onChanged();
        return this;
      }

      private long txSizeCostPerByte_ ;
      /**
       * <code>optional uint64 tx_size_cost_per_byte = 3;</code>
       */
      public long getTxSizeCostPerByte() {
        return txSizeCostPerByte_;
      }
      /**
       * <code>optional uint64 tx_size_cost_per_byte = 3;</code>
       */
      public Builder setTxSizeCostPerByte(long value) {
        
        txSizeCostPerByte_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 tx_size_cost_per_byte = 3;</code>
       */
      public Builder clearTxSizeCostPerByte() {
        
        txSizeCostPerByte_ = 0L;
        onChanged();
        return this;
      }

      private long sigVerifyCostEd25519_ ;
      /**
       * <code>optional uint64 sig_verify_cost_ed25519 = 4;</code>
       */
      public long getSigVerifyCostEd25519() {
        return sigVerifyCostEd25519_;
      }
      /**
       * <code>optional uint64 sig_verify_cost_ed25519 = 4;</code>
       */
      public Builder setSigVerifyCostEd25519(long value) {
        
        sigVerifyCostEd25519_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 sig_verify_cost_ed25519 = 4;</code>
       */
      public Builder clearSigVerifyCostEd25519() {
        
        sigVerifyCostEd25519_ = 0L;
        onChanged();
        return this;
      }

      private long sigVerifyCostSecp256K1_ ;
      /**
       * <code>optional uint64 sig_verify_cost_secp256k1 = 5;</code>
       */
      public long getSigVerifyCostSecp256K1() {
        return sigVerifyCostSecp256K1_;
      }
      /**
       * <code>optional uint64 sig_verify_cost_secp256k1 = 5;</code>
       */
      public Builder setSigVerifyCostSecp256K1(long value) {
        
        sigVerifyCostSecp256K1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 sig_verify_cost_secp256k1 = 5;</code>
       */
      public Builder clearSigVerifyCostSecp256K1() {
        
        sigVerifyCostSecp256K1_ = 0L;
        onChanged();
        return this;
      }

      private long sigVerifyCostSm2_ ;
      /**
       * <code>optional uint64 sig_verify_cost_sm2 = 6;</code>
       */
      public long getSigVerifyCostSm2() {
        return sigVerifyCostSm2_;
      }
      /**
       * <code>optional uint64 sig_verify_cost_sm2 = 6;</code>
       */
      public Builder setSigVerifyCostSm2(long value) {
        
        sigVerifyCostSm2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 sig_verify_cost_sm2 = 6;</code>
       */
      public Builder clearSigVerifyCostSm2() {
        
        sigVerifyCostSm2_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:cosmos.auth.v1beta1.Params)
    }

    // @@protoc_insertion_point(class_scope:cosmos.auth.v1beta1.Params)
    private static final cosmos.auth.v1beta1.Auth.Params DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cosmos.auth.v1beta1.Auth.Params();
    }

    public static cosmos.auth.v1beta1.Auth.Params getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Params>
        PARSER = new com.google.protobuf.AbstractParser<Params>() {
      public Params parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Params(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Params> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Params> getParserForType() {
      return PARSER;
    }

    public cosmos.auth.v1beta1.Auth.Params getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cosmos_auth_v1beta1_BaseAccount_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cosmos_auth_v1beta1_BaseAccount_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cosmos_auth_v1beta1_ModuleAccount_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cosmos_auth_v1beta1_ModuleAccount_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cosmos_auth_v1beta1_Params_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cosmos_auth_v1beta1_Params_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036cosmos/auth/v1beta1/auth.proto\022\023cosmos" +
      ".auth.v1beta1\032\031cosmos_proto/cosmos.proto" +
      "\032\024gogoproto/gogo.proto\032\031google/protobuf/" +
      "any.proto\"\323\001\n\013BaseAccount\022\017\n\007address\030\001 \001" +
      "(\t\022T\n\007pub_key\030\002 \001(\0132\024.google.protobuf.An" +
      "yB-\352\336\037\024public_key,omitempty\362\336\037\021yaml:\"pub" +
      "lic_key\"\0221\n\016account_number\030\003 \001(\004B\031\362\336\037\025ya" +
      "ml:\"account_number\"\022\020\n\010sequence\030\004 \001(\004:\030\210" +
      "\240\037\000\230\240\037\000\350\240\037\000\322\264-\010AccountI\"\243\001\n\rModuleAccoun" +
      "t\022S\n\014base_account\030\001 \001(\0132 .cosmos.auth.v1",
      "beta1.BaseAccountB\033\320\336\037\001\362\336\037\023yaml:\"base_ac" +
      "count\"\022\014\n\004name\030\002 \001(\t\022\023\n\013permissions\030\003 \003(" +
      "\t:\032\210\240\037\000\230\240\037\000\322\264-\016ModuleAccountI\"\320\003\n\006Params" +
      "\022;\n\023max_memo_characters\030\001 \001(\004B\036\362\336\037\032yaml:" +
      "\"max_memo_characters\"\022-\n\014tx_sig_limit\030\002 " +
      "\001(\004B\027\362\336\037\023yaml:\"tx_sig_limit\"\022?\n\025tx_size_" +
      "cost_per_byte\030\003 \001(\004B \362\336\037\034yaml:\"tx_size_c" +
      "ost_per_byte\"\022[\n\027sig_verify_cost_ed25519" +
      "\030\004 \001(\004B:\342\336\037\024SigVerifyCostED25519\362\336\037\036yaml" +
      ":\"sig_verify_cost_ed25519\"\022a\n\031sig_verify",
      "_cost_secp256k1\030\005 \001(\004B>\342\336\037\026SigVerifyCost" +
      "Secp256k1\362\336\037 yaml:\"sig_verify_cost_secp2" +
      "56k1\"\022O\n\023sig_verify_cost_sm2\030\006 \001(\004B2\342\336\037\020" +
      "SigVerifyCostSm2\362\336\037\032yaml:\"sig_verify_cos" +
      "t_sm2\":\010\350\240\037\001\230\240\037\000B+Z)github.com/cosmos/co" +
      "smos-sdk/x/auth/typesb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          cosmos_proto.Cosmos.getDescriptor(),
          com.google.protobuf.GoGoProtos.getDescriptor(),
          com.google.protobuf.AnyProto.getDescriptor(),
        }, assigner);
    internal_static_cosmos_auth_v1beta1_BaseAccount_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cosmos_auth_v1beta1_BaseAccount_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cosmos_auth_v1beta1_BaseAccount_descriptor,
        new java.lang.String[] { "Address", "PubKey", "AccountNumber", "Sequence", });
    internal_static_cosmos_auth_v1beta1_ModuleAccount_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_cosmos_auth_v1beta1_ModuleAccount_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cosmos_auth_v1beta1_ModuleAccount_descriptor,
        new java.lang.String[] { "BaseAccount", "Name", "Permissions", });
    internal_static_cosmos_auth_v1beta1_Params_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_cosmos_auth_v1beta1_Params_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cosmos_auth_v1beta1_Params_descriptor,
        new java.lang.String[] { "MaxMemoCharacters", "TxSigLimit", "TxSizeCostPerByte", "SigVerifyCostEd25519", "SigVerifyCostSecp256K1", "SigVerifyCostSm2", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(cosmos_proto.Cosmos.implementsInterface);
    registry.add(com.google.protobuf.GoGoProtos.customname);
    registry.add(com.google.protobuf.GoGoProtos.embed);
    registry.add(com.google.protobuf.GoGoProtos.equal);
    registry.add(com.google.protobuf.GoGoProtos.goprotoGetters);
    registry.add(com.google.protobuf.GoGoProtos.goprotoStringer);
    registry.add(com.google.protobuf.GoGoProtos.jsontag);
    registry.add(com.google.protobuf.GoGoProtos.moretags);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    cosmos_proto.Cosmos.getDescriptor();
    com.google.protobuf.GoGoProtos.getDescriptor();
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
