// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cosmos/auth/v1beta1/query.proto

package cosmos.auth.v1beta1;

public final class QueryOuterClass {
  private QueryOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface QueryAccountRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cosmos.auth.v1beta1.QueryAccountRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * address defines the address to query for.
     * </pre>
     *
     * <code>optional string address = 1;</code>
     */
    java.lang.String getAddress();
    /**
     * <pre>
     * address defines the address to query for.
     * </pre>
     *
     * <code>optional string address = 1;</code>
     */
    com.google.protobuf.ByteString
        getAddressBytes();
  }
  /**
   * <pre>
   * QueryAccountRequest is the request type for the Query/Account RPC method.
   * </pre>
   *
   * Protobuf type {@code cosmos.auth.v1beta1.QueryAccountRequest}
   */
  public  static final class QueryAccountRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cosmos.auth.v1beta1.QueryAccountRequest)
      QueryAccountRequestOrBuilder {
    // Use QueryAccountRequest.newBuilder() to construct.
    private QueryAccountRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private QueryAccountRequest() {
      address_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private QueryAccountRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              address_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cosmos.auth.v1beta1.QueryOuterClass.internal_static_cosmos_auth_v1beta1_QueryAccountRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cosmos.auth.v1beta1.QueryOuterClass.internal_static_cosmos_auth_v1beta1_QueryAccountRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cosmos.auth.v1beta1.QueryOuterClass.QueryAccountRequest.class, cosmos.auth.v1beta1.QueryOuterClass.QueryAccountRequest.Builder.class);
    }

    public static final int ADDRESS_FIELD_NUMBER = 1;
    private volatile java.lang.Object address_;
    /**
     * <pre>
     * address defines the address to query for.
     * </pre>
     *
     * <code>optional string address = 1;</code>
     */
    public java.lang.String getAddress() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        address_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * address defines the address to query for.
     * </pre>
     *
     * <code>optional string address = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAddressBytes() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getAddressBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, address_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getAddressBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, address_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cosmos.auth.v1beta1.QueryOuterClass.QueryAccountRequest)) {
        return super.equals(obj);
      }
      cosmos.auth.v1beta1.QueryOuterClass.QueryAccountRequest other = (cosmos.auth.v1beta1.QueryOuterClass.QueryAccountRequest) obj;

      boolean result = true;
      result = result && getAddress()
          .equals(other.getAddress());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddress().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cosmos.auth.v1beta1.QueryOuterClass.QueryAccountRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cosmos.auth.v1beta1.QueryOuterClass.QueryAccountRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cosmos.auth.v1beta1.QueryOuterClass.QueryAccountRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cosmos.auth.v1beta1.QueryOuterClass.QueryAccountRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cosmos.auth.v1beta1.QueryOuterClass.QueryAccountRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cosmos.auth.v1beta1.QueryOuterClass.QueryAccountRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cosmos.auth.v1beta1.QueryOuterClass.QueryAccountRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cosmos.auth.v1beta1.QueryOuterClass.QueryAccountRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cosmos.auth.v1beta1.QueryOuterClass.QueryAccountRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cosmos.auth.v1beta1.QueryOuterClass.QueryAccountRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cosmos.auth.v1beta1.QueryOuterClass.QueryAccountRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * QueryAccountRequest is the request type for the Query/Account RPC method.
     * </pre>
     *
     * Protobuf type {@code cosmos.auth.v1beta1.QueryAccountRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cosmos.auth.v1beta1.QueryAccountRequest)
        cosmos.auth.v1beta1.QueryOuterClass.QueryAccountRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cosmos.auth.v1beta1.QueryOuterClass.internal_static_cosmos_auth_v1beta1_QueryAccountRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cosmos.auth.v1beta1.QueryOuterClass.internal_static_cosmos_auth_v1beta1_QueryAccountRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cosmos.auth.v1beta1.QueryOuterClass.QueryAccountRequest.class, cosmos.auth.v1beta1.QueryOuterClass.QueryAccountRequest.Builder.class);
      }

      // Construct using cosmos.auth.v1beta1.QueryOuterClass.QueryAccountRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        address_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cosmos.auth.v1beta1.QueryOuterClass.internal_static_cosmos_auth_v1beta1_QueryAccountRequest_descriptor;
      }

      public cosmos.auth.v1beta1.QueryOuterClass.QueryAccountRequest getDefaultInstanceForType() {
        return cosmos.auth.v1beta1.QueryOuterClass.QueryAccountRequest.getDefaultInstance();
      }

      public cosmos.auth.v1beta1.QueryOuterClass.QueryAccountRequest build() {
        cosmos.auth.v1beta1.QueryOuterClass.QueryAccountRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cosmos.auth.v1beta1.QueryOuterClass.QueryAccountRequest buildPartial() {
        cosmos.auth.v1beta1.QueryOuterClass.QueryAccountRequest result = new cosmos.auth.v1beta1.QueryOuterClass.QueryAccountRequest(this);
        result.address_ = address_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cosmos.auth.v1beta1.QueryOuterClass.QueryAccountRequest) {
          return mergeFrom((cosmos.auth.v1beta1.QueryOuterClass.QueryAccountRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cosmos.auth.v1beta1.QueryOuterClass.QueryAccountRequest other) {
        if (other == cosmos.auth.v1beta1.QueryOuterClass.QueryAccountRequest.getDefaultInstance()) return this;
        if (!other.getAddress().isEmpty()) {
          address_ = other.address_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cosmos.auth.v1beta1.QueryOuterClass.QueryAccountRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cosmos.auth.v1beta1.QueryOuterClass.QueryAccountRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object address_ = "";
      /**
       * <pre>
       * address defines the address to query for.
       * </pre>
       *
       * <code>optional string address = 1;</code>
       */
      public java.lang.String getAddress() {
        java.lang.Object ref = address_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          address_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * address defines the address to query for.
       * </pre>
       *
       * <code>optional string address = 1;</code>
       */
      public com.google.protobuf.ByteString
          getAddressBytes() {
        java.lang.Object ref = address_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          address_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * address defines the address to query for.
       * </pre>
       *
       * <code>optional string address = 1;</code>
       */
      public Builder setAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        address_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * address defines the address to query for.
       * </pre>
       *
       * <code>optional string address = 1;</code>
       */
      public Builder clearAddress() {
        
        address_ = getDefaultInstance().getAddress();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * address defines the address to query for.
       * </pre>
       *
       * <code>optional string address = 1;</code>
       */
      public Builder setAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        address_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:cosmos.auth.v1beta1.QueryAccountRequest)
    }

    // @@protoc_insertion_point(class_scope:cosmos.auth.v1beta1.QueryAccountRequest)
    private static final cosmos.auth.v1beta1.QueryOuterClass.QueryAccountRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cosmos.auth.v1beta1.QueryOuterClass.QueryAccountRequest();
    }

    public static cosmos.auth.v1beta1.QueryOuterClass.QueryAccountRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<QueryAccountRequest>
        PARSER = new com.google.protobuf.AbstractParser<QueryAccountRequest>() {
      public QueryAccountRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new QueryAccountRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<QueryAccountRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<QueryAccountRequest> getParserForType() {
      return PARSER;
    }

    public cosmos.auth.v1beta1.QueryOuterClass.QueryAccountRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface QueryAccountResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cosmos.auth.v1beta1.QueryAccountResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * account defines the account of the corresponding address.
     * </pre>
     *
     * <code>optional .google.protobuf.Any account = 1;</code>
     */
    boolean hasAccount();
    /**
     * <pre>
     * account defines the account of the corresponding address.
     * </pre>
     *
     * <code>optional .google.protobuf.Any account = 1;</code>
     */
    com.google.protobuf.Any getAccount();
    /**
     * <pre>
     * account defines the account of the corresponding address.
     * </pre>
     *
     * <code>optional .google.protobuf.Any account = 1;</code>
     */
    com.google.protobuf.AnyOrBuilder getAccountOrBuilder();
  }
  /**
   * <pre>
   * QueryAccountResponse is the response type for the Query/Account RPC method.
   * </pre>
   *
   * Protobuf type {@code cosmos.auth.v1beta1.QueryAccountResponse}
   */
  public  static final class QueryAccountResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cosmos.auth.v1beta1.QueryAccountResponse)
      QueryAccountResponseOrBuilder {
    // Use QueryAccountResponse.newBuilder() to construct.
    private QueryAccountResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private QueryAccountResponse() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private QueryAccountResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.Any.Builder subBuilder = null;
              if (account_ != null) {
                subBuilder = account_.toBuilder();
              }
              account_ = input.readMessage(com.google.protobuf.Any.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(account_);
                account_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cosmos.auth.v1beta1.QueryOuterClass.internal_static_cosmos_auth_v1beta1_QueryAccountResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cosmos.auth.v1beta1.QueryOuterClass.internal_static_cosmos_auth_v1beta1_QueryAccountResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cosmos.auth.v1beta1.QueryOuterClass.QueryAccountResponse.class, cosmos.auth.v1beta1.QueryOuterClass.QueryAccountResponse.Builder.class);
    }

    public static final int ACCOUNT_FIELD_NUMBER = 1;
    private com.google.protobuf.Any account_;
    /**
     * <pre>
     * account defines the account of the corresponding address.
     * </pre>
     *
     * <code>optional .google.protobuf.Any account = 1;</code>
     */
    public boolean hasAccount() {
      return account_ != null;
    }
    /**
     * <pre>
     * account defines the account of the corresponding address.
     * </pre>
     *
     * <code>optional .google.protobuf.Any account = 1;</code>
     */
    public com.google.protobuf.Any getAccount() {
      return account_ == null ? com.google.protobuf.Any.getDefaultInstance() : account_;
    }
    /**
     * <pre>
     * account defines the account of the corresponding address.
     * </pre>
     *
     * <code>optional .google.protobuf.Any account = 1;</code>
     */
    public com.google.protobuf.AnyOrBuilder getAccountOrBuilder() {
      return getAccount();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (account_ != null) {
        output.writeMessage(1, getAccount());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (account_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getAccount());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cosmos.auth.v1beta1.QueryOuterClass.QueryAccountResponse)) {
        return super.equals(obj);
      }
      cosmos.auth.v1beta1.QueryOuterClass.QueryAccountResponse other = (cosmos.auth.v1beta1.QueryOuterClass.QueryAccountResponse) obj;

      boolean result = true;
      result = result && (hasAccount() == other.hasAccount());
      if (hasAccount()) {
        result = result && getAccount()
            .equals(other.getAccount());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasAccount()) {
        hash = (37 * hash) + ACCOUNT_FIELD_NUMBER;
        hash = (53 * hash) + getAccount().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cosmos.auth.v1beta1.QueryOuterClass.QueryAccountResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cosmos.auth.v1beta1.QueryOuterClass.QueryAccountResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cosmos.auth.v1beta1.QueryOuterClass.QueryAccountResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cosmos.auth.v1beta1.QueryOuterClass.QueryAccountResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cosmos.auth.v1beta1.QueryOuterClass.QueryAccountResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cosmos.auth.v1beta1.QueryOuterClass.QueryAccountResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cosmos.auth.v1beta1.QueryOuterClass.QueryAccountResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cosmos.auth.v1beta1.QueryOuterClass.QueryAccountResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cosmos.auth.v1beta1.QueryOuterClass.QueryAccountResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cosmos.auth.v1beta1.QueryOuterClass.QueryAccountResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cosmos.auth.v1beta1.QueryOuterClass.QueryAccountResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * QueryAccountResponse is the response type for the Query/Account RPC method.
     * </pre>
     *
     * Protobuf type {@code cosmos.auth.v1beta1.QueryAccountResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cosmos.auth.v1beta1.QueryAccountResponse)
        cosmos.auth.v1beta1.QueryOuterClass.QueryAccountResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cosmos.auth.v1beta1.QueryOuterClass.internal_static_cosmos_auth_v1beta1_QueryAccountResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cosmos.auth.v1beta1.QueryOuterClass.internal_static_cosmos_auth_v1beta1_QueryAccountResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cosmos.auth.v1beta1.QueryOuterClass.QueryAccountResponse.class, cosmos.auth.v1beta1.QueryOuterClass.QueryAccountResponse.Builder.class);
      }

      // Construct using cosmos.auth.v1beta1.QueryOuterClass.QueryAccountResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (accountBuilder_ == null) {
          account_ = null;
        } else {
          account_ = null;
          accountBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cosmos.auth.v1beta1.QueryOuterClass.internal_static_cosmos_auth_v1beta1_QueryAccountResponse_descriptor;
      }

      public cosmos.auth.v1beta1.QueryOuterClass.QueryAccountResponse getDefaultInstanceForType() {
        return cosmos.auth.v1beta1.QueryOuterClass.QueryAccountResponse.getDefaultInstance();
      }

      public cosmos.auth.v1beta1.QueryOuterClass.QueryAccountResponse build() {
        cosmos.auth.v1beta1.QueryOuterClass.QueryAccountResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cosmos.auth.v1beta1.QueryOuterClass.QueryAccountResponse buildPartial() {
        cosmos.auth.v1beta1.QueryOuterClass.QueryAccountResponse result = new cosmos.auth.v1beta1.QueryOuterClass.QueryAccountResponse(this);
        if (accountBuilder_ == null) {
          result.account_ = account_;
        } else {
          result.account_ = accountBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cosmos.auth.v1beta1.QueryOuterClass.QueryAccountResponse) {
          return mergeFrom((cosmos.auth.v1beta1.QueryOuterClass.QueryAccountResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cosmos.auth.v1beta1.QueryOuterClass.QueryAccountResponse other) {
        if (other == cosmos.auth.v1beta1.QueryOuterClass.QueryAccountResponse.getDefaultInstance()) return this;
        if (other.hasAccount()) {
          mergeAccount(other.getAccount());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cosmos.auth.v1beta1.QueryOuterClass.QueryAccountResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cosmos.auth.v1beta1.QueryOuterClass.QueryAccountResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.Any account_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> accountBuilder_;
      /**
       * <pre>
       * account defines the account of the corresponding address.
       * </pre>
       *
       * <code>optional .google.protobuf.Any account = 1;</code>
       */
      public boolean hasAccount() {
        return accountBuilder_ != null || account_ != null;
      }
      /**
       * <pre>
       * account defines the account of the corresponding address.
       * </pre>
       *
       * <code>optional .google.protobuf.Any account = 1;</code>
       */
      public com.google.protobuf.Any getAccount() {
        if (accountBuilder_ == null) {
          return account_ == null ? com.google.protobuf.Any.getDefaultInstance() : account_;
        } else {
          return accountBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * account defines the account of the corresponding address.
       * </pre>
       *
       * <code>optional .google.protobuf.Any account = 1;</code>
       */
      public Builder setAccount(com.google.protobuf.Any value) {
        if (accountBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          account_ = value;
          onChanged();
        } else {
          accountBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * account defines the account of the corresponding address.
       * </pre>
       *
       * <code>optional .google.protobuf.Any account = 1;</code>
       */
      public Builder setAccount(
          com.google.protobuf.Any.Builder builderForValue) {
        if (accountBuilder_ == null) {
          account_ = builderForValue.build();
          onChanged();
        } else {
          accountBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * account defines the account of the corresponding address.
       * </pre>
       *
       * <code>optional .google.protobuf.Any account = 1;</code>
       */
      public Builder mergeAccount(com.google.protobuf.Any value) {
        if (accountBuilder_ == null) {
          if (account_ != null) {
            account_ =
              com.google.protobuf.Any.newBuilder(account_).mergeFrom(value).buildPartial();
          } else {
            account_ = value;
          }
          onChanged();
        } else {
          accountBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * account defines the account of the corresponding address.
       * </pre>
       *
       * <code>optional .google.protobuf.Any account = 1;</code>
       */
      public Builder clearAccount() {
        if (accountBuilder_ == null) {
          account_ = null;
          onChanged();
        } else {
          account_ = null;
          accountBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * account defines the account of the corresponding address.
       * </pre>
       *
       * <code>optional .google.protobuf.Any account = 1;</code>
       */
      public com.google.protobuf.Any.Builder getAccountBuilder() {
        
        onChanged();
        return getAccountFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * account defines the account of the corresponding address.
       * </pre>
       *
       * <code>optional .google.protobuf.Any account = 1;</code>
       */
      public com.google.protobuf.AnyOrBuilder getAccountOrBuilder() {
        if (accountBuilder_ != null) {
          return accountBuilder_.getMessageOrBuilder();
        } else {
          return account_ == null ?
              com.google.protobuf.Any.getDefaultInstance() : account_;
        }
      }
      /**
       * <pre>
       * account defines the account of the corresponding address.
       * </pre>
       *
       * <code>optional .google.protobuf.Any account = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
          getAccountFieldBuilder() {
        if (accountBuilder_ == null) {
          accountBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                  getAccount(),
                  getParentForChildren(),
                  isClean());
          account_ = null;
        }
        return accountBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:cosmos.auth.v1beta1.QueryAccountResponse)
    }

    // @@protoc_insertion_point(class_scope:cosmos.auth.v1beta1.QueryAccountResponse)
    private static final cosmos.auth.v1beta1.QueryOuterClass.QueryAccountResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cosmos.auth.v1beta1.QueryOuterClass.QueryAccountResponse();
    }

    public static cosmos.auth.v1beta1.QueryOuterClass.QueryAccountResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<QueryAccountResponse>
        PARSER = new com.google.protobuf.AbstractParser<QueryAccountResponse>() {
      public QueryAccountResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new QueryAccountResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<QueryAccountResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<QueryAccountResponse> getParserForType() {
      return PARSER;
    }

    public cosmos.auth.v1beta1.QueryOuterClass.QueryAccountResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface QueryParamsRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cosmos.auth.v1beta1.QueryParamsRequest)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * <pre>
   * QueryParamsRequest is the request type for the Query/Params RPC method.
   * </pre>
   *
   * Protobuf type {@code cosmos.auth.v1beta1.QueryParamsRequest}
   */
  public  static final class QueryParamsRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cosmos.auth.v1beta1.QueryParamsRequest)
      QueryParamsRequestOrBuilder {
    // Use QueryParamsRequest.newBuilder() to construct.
    private QueryParamsRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private QueryParamsRequest() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private QueryParamsRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cosmos.auth.v1beta1.QueryOuterClass.internal_static_cosmos_auth_v1beta1_QueryParamsRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cosmos.auth.v1beta1.QueryOuterClass.internal_static_cosmos_auth_v1beta1_QueryParamsRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cosmos.auth.v1beta1.QueryOuterClass.QueryParamsRequest.class, cosmos.auth.v1beta1.QueryOuterClass.QueryParamsRequest.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cosmos.auth.v1beta1.QueryOuterClass.QueryParamsRequest)) {
        return super.equals(obj);
      }
      cosmos.auth.v1beta1.QueryOuterClass.QueryParamsRequest other = (cosmos.auth.v1beta1.QueryOuterClass.QueryParamsRequest) obj;

      boolean result = true;
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cosmos.auth.v1beta1.QueryOuterClass.QueryParamsRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cosmos.auth.v1beta1.QueryOuterClass.QueryParamsRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cosmos.auth.v1beta1.QueryOuterClass.QueryParamsRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cosmos.auth.v1beta1.QueryOuterClass.QueryParamsRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cosmos.auth.v1beta1.QueryOuterClass.QueryParamsRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cosmos.auth.v1beta1.QueryOuterClass.QueryParamsRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cosmos.auth.v1beta1.QueryOuterClass.QueryParamsRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cosmos.auth.v1beta1.QueryOuterClass.QueryParamsRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cosmos.auth.v1beta1.QueryOuterClass.QueryParamsRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cosmos.auth.v1beta1.QueryOuterClass.QueryParamsRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cosmos.auth.v1beta1.QueryOuterClass.QueryParamsRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * QueryParamsRequest is the request type for the Query/Params RPC method.
     * </pre>
     *
     * Protobuf type {@code cosmos.auth.v1beta1.QueryParamsRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cosmos.auth.v1beta1.QueryParamsRequest)
        cosmos.auth.v1beta1.QueryOuterClass.QueryParamsRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cosmos.auth.v1beta1.QueryOuterClass.internal_static_cosmos_auth_v1beta1_QueryParamsRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cosmos.auth.v1beta1.QueryOuterClass.internal_static_cosmos_auth_v1beta1_QueryParamsRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cosmos.auth.v1beta1.QueryOuterClass.QueryParamsRequest.class, cosmos.auth.v1beta1.QueryOuterClass.QueryParamsRequest.Builder.class);
      }

      // Construct using cosmos.auth.v1beta1.QueryOuterClass.QueryParamsRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cosmos.auth.v1beta1.QueryOuterClass.internal_static_cosmos_auth_v1beta1_QueryParamsRequest_descriptor;
      }

      public cosmos.auth.v1beta1.QueryOuterClass.QueryParamsRequest getDefaultInstanceForType() {
        return cosmos.auth.v1beta1.QueryOuterClass.QueryParamsRequest.getDefaultInstance();
      }

      public cosmos.auth.v1beta1.QueryOuterClass.QueryParamsRequest build() {
        cosmos.auth.v1beta1.QueryOuterClass.QueryParamsRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cosmos.auth.v1beta1.QueryOuterClass.QueryParamsRequest buildPartial() {
        cosmos.auth.v1beta1.QueryOuterClass.QueryParamsRequest result = new cosmos.auth.v1beta1.QueryOuterClass.QueryParamsRequest(this);
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cosmos.auth.v1beta1.QueryOuterClass.QueryParamsRequest) {
          return mergeFrom((cosmos.auth.v1beta1.QueryOuterClass.QueryParamsRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cosmos.auth.v1beta1.QueryOuterClass.QueryParamsRequest other) {
        if (other == cosmos.auth.v1beta1.QueryOuterClass.QueryParamsRequest.getDefaultInstance()) return this;
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cosmos.auth.v1beta1.QueryOuterClass.QueryParamsRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cosmos.auth.v1beta1.QueryOuterClass.QueryParamsRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:cosmos.auth.v1beta1.QueryParamsRequest)
    }

    // @@protoc_insertion_point(class_scope:cosmos.auth.v1beta1.QueryParamsRequest)
    private static final cosmos.auth.v1beta1.QueryOuterClass.QueryParamsRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cosmos.auth.v1beta1.QueryOuterClass.QueryParamsRequest();
    }

    public static cosmos.auth.v1beta1.QueryOuterClass.QueryParamsRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<QueryParamsRequest>
        PARSER = new com.google.protobuf.AbstractParser<QueryParamsRequest>() {
      public QueryParamsRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new QueryParamsRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<QueryParamsRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<QueryParamsRequest> getParserForType() {
      return PARSER;
    }

    public cosmos.auth.v1beta1.QueryOuterClass.QueryParamsRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface QueryParamsResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cosmos.auth.v1beta1.QueryParamsResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * params defines the parameters of the module.
     * </pre>
     *
     * <code>optional .cosmos.auth.v1beta1.Params params = 1;</code>
     */
    boolean hasParams();
    /**
     * <pre>
     * params defines the parameters of the module.
     * </pre>
     *
     * <code>optional .cosmos.auth.v1beta1.Params params = 1;</code>
     */
    cosmos.auth.v1beta1.Auth.Params getParams();
    /**
     * <pre>
     * params defines the parameters of the module.
     * </pre>
     *
     * <code>optional .cosmos.auth.v1beta1.Params params = 1;</code>
     */
    cosmos.auth.v1beta1.Auth.ParamsOrBuilder getParamsOrBuilder();
  }
  /**
   * <pre>
   * QueryParamsResponse is the response type for the Query/Params RPC method.
   * </pre>
   *
   * Protobuf type {@code cosmos.auth.v1beta1.QueryParamsResponse}
   */
  public  static final class QueryParamsResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cosmos.auth.v1beta1.QueryParamsResponse)
      QueryParamsResponseOrBuilder {
    // Use QueryParamsResponse.newBuilder() to construct.
    private QueryParamsResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private QueryParamsResponse() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private QueryParamsResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              cosmos.auth.v1beta1.Auth.Params.Builder subBuilder = null;
              if (params_ != null) {
                subBuilder = params_.toBuilder();
              }
              params_ = input.readMessage(cosmos.auth.v1beta1.Auth.Params.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(params_);
                params_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cosmos.auth.v1beta1.QueryOuterClass.internal_static_cosmos_auth_v1beta1_QueryParamsResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cosmos.auth.v1beta1.QueryOuterClass.internal_static_cosmos_auth_v1beta1_QueryParamsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cosmos.auth.v1beta1.QueryOuterClass.QueryParamsResponse.class, cosmos.auth.v1beta1.QueryOuterClass.QueryParamsResponse.Builder.class);
    }

    public static final int PARAMS_FIELD_NUMBER = 1;
    private cosmos.auth.v1beta1.Auth.Params params_;
    /**
     * <pre>
     * params defines the parameters of the module.
     * </pre>
     *
     * <code>optional .cosmos.auth.v1beta1.Params params = 1;</code>
     */
    public boolean hasParams() {
      return params_ != null;
    }
    /**
     * <pre>
     * params defines the parameters of the module.
     * </pre>
     *
     * <code>optional .cosmos.auth.v1beta1.Params params = 1;</code>
     */
    public cosmos.auth.v1beta1.Auth.Params getParams() {
      return params_ == null ? cosmos.auth.v1beta1.Auth.Params.getDefaultInstance() : params_;
    }
    /**
     * <pre>
     * params defines the parameters of the module.
     * </pre>
     *
     * <code>optional .cosmos.auth.v1beta1.Params params = 1;</code>
     */
    public cosmos.auth.v1beta1.Auth.ParamsOrBuilder getParamsOrBuilder() {
      return getParams();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (params_ != null) {
        output.writeMessage(1, getParams());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (params_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getParams());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cosmos.auth.v1beta1.QueryOuterClass.QueryParamsResponse)) {
        return super.equals(obj);
      }
      cosmos.auth.v1beta1.QueryOuterClass.QueryParamsResponse other = (cosmos.auth.v1beta1.QueryOuterClass.QueryParamsResponse) obj;

      boolean result = true;
      result = result && (hasParams() == other.hasParams());
      if (hasParams()) {
        result = result && getParams()
            .equals(other.getParams());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasParams()) {
        hash = (37 * hash) + PARAMS_FIELD_NUMBER;
        hash = (53 * hash) + getParams().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cosmos.auth.v1beta1.QueryOuterClass.QueryParamsResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cosmos.auth.v1beta1.QueryOuterClass.QueryParamsResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cosmos.auth.v1beta1.QueryOuterClass.QueryParamsResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cosmos.auth.v1beta1.QueryOuterClass.QueryParamsResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cosmos.auth.v1beta1.QueryOuterClass.QueryParamsResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cosmos.auth.v1beta1.QueryOuterClass.QueryParamsResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cosmos.auth.v1beta1.QueryOuterClass.QueryParamsResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cosmos.auth.v1beta1.QueryOuterClass.QueryParamsResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cosmos.auth.v1beta1.QueryOuterClass.QueryParamsResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cosmos.auth.v1beta1.QueryOuterClass.QueryParamsResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cosmos.auth.v1beta1.QueryOuterClass.QueryParamsResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * QueryParamsResponse is the response type for the Query/Params RPC method.
     * </pre>
     *
     * Protobuf type {@code cosmos.auth.v1beta1.QueryParamsResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cosmos.auth.v1beta1.QueryParamsResponse)
        cosmos.auth.v1beta1.QueryOuterClass.QueryParamsResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cosmos.auth.v1beta1.QueryOuterClass.internal_static_cosmos_auth_v1beta1_QueryParamsResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cosmos.auth.v1beta1.QueryOuterClass.internal_static_cosmos_auth_v1beta1_QueryParamsResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cosmos.auth.v1beta1.QueryOuterClass.QueryParamsResponse.class, cosmos.auth.v1beta1.QueryOuterClass.QueryParamsResponse.Builder.class);
      }

      // Construct using cosmos.auth.v1beta1.QueryOuterClass.QueryParamsResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (paramsBuilder_ == null) {
          params_ = null;
        } else {
          params_ = null;
          paramsBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cosmos.auth.v1beta1.QueryOuterClass.internal_static_cosmos_auth_v1beta1_QueryParamsResponse_descriptor;
      }

      public cosmos.auth.v1beta1.QueryOuterClass.QueryParamsResponse getDefaultInstanceForType() {
        return cosmos.auth.v1beta1.QueryOuterClass.QueryParamsResponse.getDefaultInstance();
      }

      public cosmos.auth.v1beta1.QueryOuterClass.QueryParamsResponse build() {
        cosmos.auth.v1beta1.QueryOuterClass.QueryParamsResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cosmos.auth.v1beta1.QueryOuterClass.QueryParamsResponse buildPartial() {
        cosmos.auth.v1beta1.QueryOuterClass.QueryParamsResponse result = new cosmos.auth.v1beta1.QueryOuterClass.QueryParamsResponse(this);
        if (paramsBuilder_ == null) {
          result.params_ = params_;
        } else {
          result.params_ = paramsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cosmos.auth.v1beta1.QueryOuterClass.QueryParamsResponse) {
          return mergeFrom((cosmos.auth.v1beta1.QueryOuterClass.QueryParamsResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cosmos.auth.v1beta1.QueryOuterClass.QueryParamsResponse other) {
        if (other == cosmos.auth.v1beta1.QueryOuterClass.QueryParamsResponse.getDefaultInstance()) return this;
        if (other.hasParams()) {
          mergeParams(other.getParams());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cosmos.auth.v1beta1.QueryOuterClass.QueryParamsResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cosmos.auth.v1beta1.QueryOuterClass.QueryParamsResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private cosmos.auth.v1beta1.Auth.Params params_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          cosmos.auth.v1beta1.Auth.Params, cosmos.auth.v1beta1.Auth.Params.Builder, cosmos.auth.v1beta1.Auth.ParamsOrBuilder> paramsBuilder_;
      /**
       * <pre>
       * params defines the parameters of the module.
       * </pre>
       *
       * <code>optional .cosmos.auth.v1beta1.Params params = 1;</code>
       */
      public boolean hasParams() {
        return paramsBuilder_ != null || params_ != null;
      }
      /**
       * <pre>
       * params defines the parameters of the module.
       * </pre>
       *
       * <code>optional .cosmos.auth.v1beta1.Params params = 1;</code>
       */
      public cosmos.auth.v1beta1.Auth.Params getParams() {
        if (paramsBuilder_ == null) {
          return params_ == null ? cosmos.auth.v1beta1.Auth.Params.getDefaultInstance() : params_;
        } else {
          return paramsBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * params defines the parameters of the module.
       * </pre>
       *
       * <code>optional .cosmos.auth.v1beta1.Params params = 1;</code>
       */
      public Builder setParams(cosmos.auth.v1beta1.Auth.Params value) {
        if (paramsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          params_ = value;
          onChanged();
        } else {
          paramsBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * params defines the parameters of the module.
       * </pre>
       *
       * <code>optional .cosmos.auth.v1beta1.Params params = 1;</code>
       */
      public Builder setParams(
          cosmos.auth.v1beta1.Auth.Params.Builder builderForValue) {
        if (paramsBuilder_ == null) {
          params_ = builderForValue.build();
          onChanged();
        } else {
          paramsBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * params defines the parameters of the module.
       * </pre>
       *
       * <code>optional .cosmos.auth.v1beta1.Params params = 1;</code>
       */
      public Builder mergeParams(cosmos.auth.v1beta1.Auth.Params value) {
        if (paramsBuilder_ == null) {
          if (params_ != null) {
            params_ =
              cosmos.auth.v1beta1.Auth.Params.newBuilder(params_).mergeFrom(value).buildPartial();
          } else {
            params_ = value;
          }
          onChanged();
        } else {
          paramsBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * params defines the parameters of the module.
       * </pre>
       *
       * <code>optional .cosmos.auth.v1beta1.Params params = 1;</code>
       */
      public Builder clearParams() {
        if (paramsBuilder_ == null) {
          params_ = null;
          onChanged();
        } else {
          params_ = null;
          paramsBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * params defines the parameters of the module.
       * </pre>
       *
       * <code>optional .cosmos.auth.v1beta1.Params params = 1;</code>
       */
      public cosmos.auth.v1beta1.Auth.Params.Builder getParamsBuilder() {
        
        onChanged();
        return getParamsFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * params defines the parameters of the module.
       * </pre>
       *
       * <code>optional .cosmos.auth.v1beta1.Params params = 1;</code>
       */
      public cosmos.auth.v1beta1.Auth.ParamsOrBuilder getParamsOrBuilder() {
        if (paramsBuilder_ != null) {
          return paramsBuilder_.getMessageOrBuilder();
        } else {
          return params_ == null ?
              cosmos.auth.v1beta1.Auth.Params.getDefaultInstance() : params_;
        }
      }
      /**
       * <pre>
       * params defines the parameters of the module.
       * </pre>
       *
       * <code>optional .cosmos.auth.v1beta1.Params params = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          cosmos.auth.v1beta1.Auth.Params, cosmos.auth.v1beta1.Auth.Params.Builder, cosmos.auth.v1beta1.Auth.ParamsOrBuilder> 
          getParamsFieldBuilder() {
        if (paramsBuilder_ == null) {
          paramsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              cosmos.auth.v1beta1.Auth.Params, cosmos.auth.v1beta1.Auth.Params.Builder, cosmos.auth.v1beta1.Auth.ParamsOrBuilder>(
                  getParams(),
                  getParentForChildren(),
                  isClean());
          params_ = null;
        }
        return paramsBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:cosmos.auth.v1beta1.QueryParamsResponse)
    }

    // @@protoc_insertion_point(class_scope:cosmos.auth.v1beta1.QueryParamsResponse)
    private static final cosmos.auth.v1beta1.QueryOuterClass.QueryParamsResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cosmos.auth.v1beta1.QueryOuterClass.QueryParamsResponse();
    }

    public static cosmos.auth.v1beta1.QueryOuterClass.QueryParamsResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<QueryParamsResponse>
        PARSER = new com.google.protobuf.AbstractParser<QueryParamsResponse>() {
      public QueryParamsResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new QueryParamsResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<QueryParamsResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<QueryParamsResponse> getParserForType() {
      return PARSER;
    }

    public cosmos.auth.v1beta1.QueryOuterClass.QueryParamsResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cosmos_auth_v1beta1_QueryAccountRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cosmos_auth_v1beta1_QueryAccountRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cosmos_auth_v1beta1_QueryAccountResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cosmos_auth_v1beta1_QueryAccountResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cosmos_auth_v1beta1_QueryParamsRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cosmos_auth_v1beta1_QueryParamsRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cosmos_auth_v1beta1_QueryParamsResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cosmos_auth_v1beta1_QueryParamsResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037cosmos/auth/v1beta1/query.proto\022\023cosmo" +
      "s.auth.v1beta1\032\024gogoproto/gogo.proto\032\031go" +
      "ogle/protobuf/any.proto\032\034google/api/anno" +
      "tations.proto\032\036cosmos/auth/v1beta1/auth." +
      "proto\032\031cosmos_proto/cosmos.proto\"0\n\023Quer" +
      "yAccountRequest\022\017\n\007address\030\001 \001(\t:\010\350\240\037\000\210\240" +
      "\037\000\"K\n\024QueryAccountResponse\0223\n\007account\030\001 " +
      "\001(\0132\024.google.protobuf.AnyB\014\312\264-\010AccountI\"" +
      "\024\n\022QueryParamsRequest\"H\n\023QueryParamsResp" +
      "onse\0221\n\006params\030\001 \001(\0132\033.cosmos.auth.v1bet",
      "a1.ParamsB\004\310\336\037\0002\234\002\n\005Query\022\217\001\n\007Account\022(." +
      "cosmos.auth.v1beta1.QueryAccountRequest\032" +
      ").cosmos.auth.v1beta1.QueryAccountRespon" +
      "se\"/\202\323\344\223\002)\022\'/cosmos/auth/v1beta1/account" +
      "s/{address}\022\200\001\n\006Params\022\'.cosmos.auth.v1b" +
      "eta1.QueryParamsRequest\032(.cosmos.auth.v1" +
      "beta1.QueryParamsResponse\"#\202\323\344\223\002\035\022\033/cosm" +
      "os/auth/v1beta1/paramsB+Z)github.com/cos" +
      "mos/cosmos-sdk/x/auth/typesb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.GoGoProtos.getDescriptor(),
          com.google.protobuf.AnyProto.getDescriptor(),
          com.google.api.AnnotationsProto.getDescriptor(),
          cosmos.auth.v1beta1.Auth.getDescriptor(),
          cosmos_proto.Cosmos.getDescriptor(),
        }, assigner);
    internal_static_cosmos_auth_v1beta1_QueryAccountRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cosmos_auth_v1beta1_QueryAccountRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cosmos_auth_v1beta1_QueryAccountRequest_descriptor,
        new java.lang.String[] { "Address", });
    internal_static_cosmos_auth_v1beta1_QueryAccountResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_cosmos_auth_v1beta1_QueryAccountResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cosmos_auth_v1beta1_QueryAccountResponse_descriptor,
        new java.lang.String[] { "Account", });
    internal_static_cosmos_auth_v1beta1_QueryParamsRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_cosmos_auth_v1beta1_QueryParamsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cosmos_auth_v1beta1_QueryParamsRequest_descriptor,
        new java.lang.String[] { });
    internal_static_cosmos_auth_v1beta1_QueryParamsResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_cosmos_auth_v1beta1_QueryParamsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cosmos_auth_v1beta1_QueryParamsResponse_descriptor,
        new java.lang.String[] { "Params", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(cosmos_proto.Cosmos.acceptsInterface);
    registry.add(com.google.protobuf.GoGoProtos.equal);
    registry.add(com.google.protobuf.GoGoProtos.goprotoGetters);
    registry.add(com.google.protobuf.GoGoProtos.nullable);
    registry.add(com.google.api.AnnotationsProto.http);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.protobuf.GoGoProtos.getDescriptor();
    com.google.protobuf.AnyProto.getDescriptor();
    com.google.api.AnnotationsProto.getDescriptor();
    cosmos.auth.v1beta1.Auth.getDescriptor();
    cosmos_proto.Cosmos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
