// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: opb/opb.proto

package irita.opb;

public final class Opb {
  private Opb() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ParamsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:irita.opb.Params)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string base_token_denom = 1;</code>
     */
    java.lang.String getBaseTokenDenom();
    /**
     * <code>optional string base_token_denom = 1;</code>
     */
    com.google.protobuf.ByteString
        getBaseTokenDenomBytes();

    /**
     * <code>optional string point_token_denom = 2;</code>
     */
    java.lang.String getPointTokenDenom();
    /**
     * <code>optional string point_token_denom = 2;</code>
     */
    com.google.protobuf.ByteString
        getPointTokenDenomBytes();

    /**
     * <code>optional string base_token_manager = 3;</code>
     */
    java.lang.String getBaseTokenManager();
    /**
     * <code>optional string base_token_manager = 3;</code>
     */
    com.google.protobuf.ByteString
        getBaseTokenManagerBytes();

    /**
     * <code>optional bool unrestricted_token_transfer = 4;</code>
     */
    boolean getUnrestrictedTokenTransfer();
  }
  /**
   * <pre>
   * Params defines the parameters for the OPB module.
   * </pre>
   *
   * Protobuf type {@code irita.opb.Params}
   */
  public  static final class Params extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:irita.opb.Params)
      ParamsOrBuilder {
    // Use Params.newBuilder() to construct.
    private Params(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Params() {
      baseTokenDenom_ = "";
      pointTokenDenom_ = "";
      baseTokenManager_ = "";
      unrestrictedTokenTransfer_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Params(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              baseTokenDenom_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              pointTokenDenom_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              baseTokenManager_ = s;
              break;
            }
            case 32: {

              unrestrictedTokenTransfer_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return irita.opb.Opb.internal_static_irita_opb_Params_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return irita.opb.Opb.internal_static_irita_opb_Params_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              irita.opb.Opb.Params.class, irita.opb.Opb.Params.Builder.class);
    }

    public static final int BASE_TOKEN_DENOM_FIELD_NUMBER = 1;
    private volatile java.lang.Object baseTokenDenom_;
    /**
     * <code>optional string base_token_denom = 1;</code>
     */
    public java.lang.String getBaseTokenDenom() {
      java.lang.Object ref = baseTokenDenom_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        baseTokenDenom_ = s;
        return s;
      }
    }
    /**
     * <code>optional string base_token_denom = 1;</code>
     */
    public com.google.protobuf.ByteString
        getBaseTokenDenomBytes() {
      java.lang.Object ref = baseTokenDenom_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        baseTokenDenom_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int POINT_TOKEN_DENOM_FIELD_NUMBER = 2;
    private volatile java.lang.Object pointTokenDenom_;
    /**
     * <code>optional string point_token_denom = 2;</code>
     */
    public java.lang.String getPointTokenDenom() {
      java.lang.Object ref = pointTokenDenom_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pointTokenDenom_ = s;
        return s;
      }
    }
    /**
     * <code>optional string point_token_denom = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPointTokenDenomBytes() {
      java.lang.Object ref = pointTokenDenom_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pointTokenDenom_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BASE_TOKEN_MANAGER_FIELD_NUMBER = 3;
    private volatile java.lang.Object baseTokenManager_;
    /**
     * <code>optional string base_token_manager = 3;</code>
     */
    public java.lang.String getBaseTokenManager() {
      java.lang.Object ref = baseTokenManager_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        baseTokenManager_ = s;
        return s;
      }
    }
    /**
     * <code>optional string base_token_manager = 3;</code>
     */
    public com.google.protobuf.ByteString
        getBaseTokenManagerBytes() {
      java.lang.Object ref = baseTokenManager_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        baseTokenManager_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int UNRESTRICTED_TOKEN_TRANSFER_FIELD_NUMBER = 4;
    private boolean unrestrictedTokenTransfer_;
    /**
     * <code>optional bool unrestricted_token_transfer = 4;</code>
     */
    public boolean getUnrestrictedTokenTransfer() {
      return unrestrictedTokenTransfer_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getBaseTokenDenomBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, baseTokenDenom_);
      }
      if (!getPointTokenDenomBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, pointTokenDenom_);
      }
      if (!getBaseTokenManagerBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, baseTokenManager_);
      }
      if (unrestrictedTokenTransfer_ != false) {
        output.writeBool(4, unrestrictedTokenTransfer_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getBaseTokenDenomBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, baseTokenDenom_);
      }
      if (!getPointTokenDenomBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, pointTokenDenom_);
      }
      if (!getBaseTokenManagerBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, baseTokenManager_);
      }
      if (unrestrictedTokenTransfer_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, unrestrictedTokenTransfer_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof irita.opb.Opb.Params)) {
        return super.equals(obj);
      }
      irita.opb.Opb.Params other = (irita.opb.Opb.Params) obj;

      boolean result = true;
      result = result && getBaseTokenDenom()
          .equals(other.getBaseTokenDenom());
      result = result && getPointTokenDenom()
          .equals(other.getPointTokenDenom());
      result = result && getBaseTokenManager()
          .equals(other.getBaseTokenManager());
      result = result && (getUnrestrictedTokenTransfer()
          == other.getUnrestrictedTokenTransfer());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + BASE_TOKEN_DENOM_FIELD_NUMBER;
      hash = (53 * hash) + getBaseTokenDenom().hashCode();
      hash = (37 * hash) + POINT_TOKEN_DENOM_FIELD_NUMBER;
      hash = (53 * hash) + getPointTokenDenom().hashCode();
      hash = (37 * hash) + BASE_TOKEN_MANAGER_FIELD_NUMBER;
      hash = (53 * hash) + getBaseTokenManager().hashCode();
      hash = (37 * hash) + UNRESTRICTED_TOKEN_TRANSFER_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getUnrestrictedTokenTransfer());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static irita.opb.Opb.Params parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static irita.opb.Opb.Params parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static irita.opb.Opb.Params parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static irita.opb.Opb.Params parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static irita.opb.Opb.Params parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static irita.opb.Opb.Params parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static irita.opb.Opb.Params parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static irita.opb.Opb.Params parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static irita.opb.Opb.Params parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static irita.opb.Opb.Params parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(irita.opb.Opb.Params prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Params defines the parameters for the OPB module.
     * </pre>
     *
     * Protobuf type {@code irita.opb.Params}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:irita.opb.Params)
        irita.opb.Opb.ParamsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return irita.opb.Opb.internal_static_irita_opb_Params_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return irita.opb.Opb.internal_static_irita_opb_Params_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                irita.opb.Opb.Params.class, irita.opb.Opb.Params.Builder.class);
      }

      // Construct using irita.opb.Opb.Params.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        baseTokenDenom_ = "";

        pointTokenDenom_ = "";

        baseTokenManager_ = "";

        unrestrictedTokenTransfer_ = false;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return irita.opb.Opb.internal_static_irita_opb_Params_descriptor;
      }

      public irita.opb.Opb.Params getDefaultInstanceForType() {
        return irita.opb.Opb.Params.getDefaultInstance();
      }

      public irita.opb.Opb.Params build() {
        irita.opb.Opb.Params result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public irita.opb.Opb.Params buildPartial() {
        irita.opb.Opb.Params result = new irita.opb.Opb.Params(this);
        result.baseTokenDenom_ = baseTokenDenom_;
        result.pointTokenDenom_ = pointTokenDenom_;
        result.baseTokenManager_ = baseTokenManager_;
        result.unrestrictedTokenTransfer_ = unrestrictedTokenTransfer_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof irita.opb.Opb.Params) {
          return mergeFrom((irita.opb.Opb.Params)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(irita.opb.Opb.Params other) {
        if (other == irita.opb.Opb.Params.getDefaultInstance()) return this;
        if (!other.getBaseTokenDenom().isEmpty()) {
          baseTokenDenom_ = other.baseTokenDenom_;
          onChanged();
        }
        if (!other.getPointTokenDenom().isEmpty()) {
          pointTokenDenom_ = other.pointTokenDenom_;
          onChanged();
        }
        if (!other.getBaseTokenManager().isEmpty()) {
          baseTokenManager_ = other.baseTokenManager_;
          onChanged();
        }
        if (other.getUnrestrictedTokenTransfer() != false) {
          setUnrestrictedTokenTransfer(other.getUnrestrictedTokenTransfer());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        irita.opb.Opb.Params parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (irita.opb.Opb.Params) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object baseTokenDenom_ = "";
      /**
       * <code>optional string base_token_denom = 1;</code>
       */
      public java.lang.String getBaseTokenDenom() {
        java.lang.Object ref = baseTokenDenom_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          baseTokenDenom_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string base_token_denom = 1;</code>
       */
      public com.google.protobuf.ByteString
          getBaseTokenDenomBytes() {
        java.lang.Object ref = baseTokenDenom_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          baseTokenDenom_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string base_token_denom = 1;</code>
       */
      public Builder setBaseTokenDenom(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        baseTokenDenom_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string base_token_denom = 1;</code>
       */
      public Builder clearBaseTokenDenom() {
        
        baseTokenDenom_ = getDefaultInstance().getBaseTokenDenom();
        onChanged();
        return this;
      }
      /**
       * <code>optional string base_token_denom = 1;</code>
       */
      public Builder setBaseTokenDenomBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        baseTokenDenom_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object pointTokenDenom_ = "";
      /**
       * <code>optional string point_token_denom = 2;</code>
       */
      public java.lang.String getPointTokenDenom() {
        java.lang.Object ref = pointTokenDenom_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          pointTokenDenom_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string point_token_denom = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPointTokenDenomBytes() {
        java.lang.Object ref = pointTokenDenom_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          pointTokenDenom_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string point_token_denom = 2;</code>
       */
      public Builder setPointTokenDenom(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        pointTokenDenom_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string point_token_denom = 2;</code>
       */
      public Builder clearPointTokenDenom() {
        
        pointTokenDenom_ = getDefaultInstance().getPointTokenDenom();
        onChanged();
        return this;
      }
      /**
       * <code>optional string point_token_denom = 2;</code>
       */
      public Builder setPointTokenDenomBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        pointTokenDenom_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object baseTokenManager_ = "";
      /**
       * <code>optional string base_token_manager = 3;</code>
       */
      public java.lang.String getBaseTokenManager() {
        java.lang.Object ref = baseTokenManager_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          baseTokenManager_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string base_token_manager = 3;</code>
       */
      public com.google.protobuf.ByteString
          getBaseTokenManagerBytes() {
        java.lang.Object ref = baseTokenManager_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          baseTokenManager_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string base_token_manager = 3;</code>
       */
      public Builder setBaseTokenManager(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        baseTokenManager_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string base_token_manager = 3;</code>
       */
      public Builder clearBaseTokenManager() {
        
        baseTokenManager_ = getDefaultInstance().getBaseTokenManager();
        onChanged();
        return this;
      }
      /**
       * <code>optional string base_token_manager = 3;</code>
       */
      public Builder setBaseTokenManagerBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        baseTokenManager_ = value;
        onChanged();
        return this;
      }

      private boolean unrestrictedTokenTransfer_ ;
      /**
       * <code>optional bool unrestricted_token_transfer = 4;</code>
       */
      public boolean getUnrestrictedTokenTransfer() {
        return unrestrictedTokenTransfer_;
      }
      /**
       * <code>optional bool unrestricted_token_transfer = 4;</code>
       */
      public Builder setUnrestrictedTokenTransfer(boolean value) {
        
        unrestrictedTokenTransfer_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool unrestricted_token_transfer = 4;</code>
       */
      public Builder clearUnrestrictedTokenTransfer() {
        
        unrestrictedTokenTransfer_ = false;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:irita.opb.Params)
    }

    // @@protoc_insertion_point(class_scope:irita.opb.Params)
    private static final irita.opb.Opb.Params DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new irita.opb.Opb.Params();
    }

    public static irita.opb.Opb.Params getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Params>
        PARSER = new com.google.protobuf.AbstractParser<Params>() {
      public Params parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Params(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Params> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Params> getParserForType() {
      return PARSER;
    }

    public irita.opb.Opb.Params getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_irita_opb_Params_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_irita_opb_Params_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ropb/opb.proto\022\tirita.opb\032\024gogoproto/go" +
      "go.proto\"\212\002\n\006Params\0225\n\020base_token_denom\030" +
      "\001 \001(\tB\033\362\336\037\027yaml:\"base_token_denom\"\0227\n\021po" +
      "int_token_denom\030\002 \001(\tB\034\362\336\037\030yaml:\"point_t" +
      "oken_denom\"\0229\n\022base_token_manager\030\003 \001(\tB" +
      "\035\362\336\037\031yaml:\"base_token_manager\"\022K\n\033unrest" +
      "ricted_token_transfer\030\004 \001(\010B&\362\336\037\"yaml:\"u" +
      "nrestricted_token_transfer\":\010\350\240\037\001\230\240\037\000B2Z" +
      ",github.com/bianjieai/irita/modules/opb/" +
      "types\310\341\036\000b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.GoGoProtos.getDescriptor(),
        }, assigner);
    internal_static_irita_opb_Params_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_irita_opb_Params_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_irita_opb_Params_descriptor,
        new java.lang.String[] { "BaseTokenDenom", "PointTokenDenom", "BaseTokenManager", "UnrestrictedTokenTransfer", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.protobuf.GoGoProtos.equal);
    registry.add(com.google.protobuf.GoGoProtos.goprotoGettersAll);
    registry.add(com.google.protobuf.GoGoProtos.goprotoStringer);
    registry.add(com.google.protobuf.GoGoProtos.moretags);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.protobuf.GoGoProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
