// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: opb/query.proto

package irita.opb;

public final class QueryOuterClass {
  private QueryOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface QueryParamsRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:irita.opb.QueryParamsRequest)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * <pre>
   * QueryParamsRequest is the request type for the Query/Params RPC method
   * </pre>
   *
   * Protobuf type {@code irita.opb.QueryParamsRequest}
   */
  public  static final class QueryParamsRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:irita.opb.QueryParamsRequest)
      QueryParamsRequestOrBuilder {
    // Use QueryParamsRequest.newBuilder() to construct.
    private QueryParamsRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private QueryParamsRequest() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private QueryParamsRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return irita.opb.QueryOuterClass.internal_static_irita_opb_QueryParamsRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return irita.opb.QueryOuterClass.internal_static_irita_opb_QueryParamsRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              irita.opb.QueryOuterClass.QueryParamsRequest.class, irita.opb.QueryOuterClass.QueryParamsRequest.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof irita.opb.QueryOuterClass.QueryParamsRequest)) {
        return super.equals(obj);
      }
      irita.opb.QueryOuterClass.QueryParamsRequest other = (irita.opb.QueryOuterClass.QueryParamsRequest) obj;

      boolean result = true;
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static irita.opb.QueryOuterClass.QueryParamsRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static irita.opb.QueryOuterClass.QueryParamsRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static irita.opb.QueryOuterClass.QueryParamsRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static irita.opb.QueryOuterClass.QueryParamsRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static irita.opb.QueryOuterClass.QueryParamsRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static irita.opb.QueryOuterClass.QueryParamsRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static irita.opb.QueryOuterClass.QueryParamsRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static irita.opb.QueryOuterClass.QueryParamsRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static irita.opb.QueryOuterClass.QueryParamsRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static irita.opb.QueryOuterClass.QueryParamsRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(irita.opb.QueryOuterClass.QueryParamsRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * QueryParamsRequest is the request type for the Query/Params RPC method
     * </pre>
     *
     * Protobuf type {@code irita.opb.QueryParamsRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:irita.opb.QueryParamsRequest)
        irita.opb.QueryOuterClass.QueryParamsRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return irita.opb.QueryOuterClass.internal_static_irita_opb_QueryParamsRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return irita.opb.QueryOuterClass.internal_static_irita_opb_QueryParamsRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                irita.opb.QueryOuterClass.QueryParamsRequest.class, irita.opb.QueryOuterClass.QueryParamsRequest.Builder.class);
      }

      // Construct using irita.opb.QueryOuterClass.QueryParamsRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return irita.opb.QueryOuterClass.internal_static_irita_opb_QueryParamsRequest_descriptor;
      }

      public irita.opb.QueryOuterClass.QueryParamsRequest getDefaultInstanceForType() {
        return irita.opb.QueryOuterClass.QueryParamsRequest.getDefaultInstance();
      }

      public irita.opb.QueryOuterClass.QueryParamsRequest build() {
        irita.opb.QueryOuterClass.QueryParamsRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public irita.opb.QueryOuterClass.QueryParamsRequest buildPartial() {
        irita.opb.QueryOuterClass.QueryParamsRequest result = new irita.opb.QueryOuterClass.QueryParamsRequest(this);
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof irita.opb.QueryOuterClass.QueryParamsRequest) {
          return mergeFrom((irita.opb.QueryOuterClass.QueryParamsRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(irita.opb.QueryOuterClass.QueryParamsRequest other) {
        if (other == irita.opb.QueryOuterClass.QueryParamsRequest.getDefaultInstance()) return this;
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        irita.opb.QueryOuterClass.QueryParamsRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (irita.opb.QueryOuterClass.QueryParamsRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:irita.opb.QueryParamsRequest)
    }

    // @@protoc_insertion_point(class_scope:irita.opb.QueryParamsRequest)
    private static final irita.opb.QueryOuterClass.QueryParamsRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new irita.opb.QueryOuterClass.QueryParamsRequest();
    }

    public static irita.opb.QueryOuterClass.QueryParamsRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<QueryParamsRequest>
        PARSER = new com.google.protobuf.AbstractParser<QueryParamsRequest>() {
      public QueryParamsRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new QueryParamsRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<QueryParamsRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<QueryParamsRequest> getParserForType() {
      return PARSER;
    }

    public irita.opb.QueryOuterClass.QueryParamsRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface QueryParamsResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:irita.opb.QueryParamsResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .irita.opb.Params params = 1;</code>
     */
    boolean hasParams();
    /**
     * <code>optional .irita.opb.Params params = 1;</code>
     */
    irita.opb.Opb.Params getParams();
    /**
     * <code>optional .irita.opb.Params params = 1;</code>
     */
    irita.opb.Opb.ParamsOrBuilder getParamsOrBuilder();
  }
  /**
   * <pre>
   * QueryParamsResponse is the response type for the Query/Params RPC method
   * </pre>
   *
   * Protobuf type {@code irita.opb.QueryParamsResponse}
   */
  public  static final class QueryParamsResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:irita.opb.QueryParamsResponse)
      QueryParamsResponseOrBuilder {
    // Use QueryParamsResponse.newBuilder() to construct.
    private QueryParamsResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private QueryParamsResponse() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private QueryParamsResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              irita.opb.Opb.Params.Builder subBuilder = null;
              if (params_ != null) {
                subBuilder = params_.toBuilder();
              }
              params_ = input.readMessage(irita.opb.Opb.Params.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(params_);
                params_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return irita.opb.QueryOuterClass.internal_static_irita_opb_QueryParamsResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return irita.opb.QueryOuterClass.internal_static_irita_opb_QueryParamsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              irita.opb.QueryOuterClass.QueryParamsResponse.class, irita.opb.QueryOuterClass.QueryParamsResponse.Builder.class);
    }

    public static final int PARAMS_FIELD_NUMBER = 1;
    private irita.opb.Opb.Params params_;
    /**
     * <code>optional .irita.opb.Params params = 1;</code>
     */
    public boolean hasParams() {
      return params_ != null;
    }
    /**
     * <code>optional .irita.opb.Params params = 1;</code>
     */
    public irita.opb.Opb.Params getParams() {
      return params_ == null ? irita.opb.Opb.Params.getDefaultInstance() : params_;
    }
    /**
     * <code>optional .irita.opb.Params params = 1;</code>
     */
    public irita.opb.Opb.ParamsOrBuilder getParamsOrBuilder() {
      return getParams();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (params_ != null) {
        output.writeMessage(1, getParams());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (params_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getParams());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof irita.opb.QueryOuterClass.QueryParamsResponse)) {
        return super.equals(obj);
      }
      irita.opb.QueryOuterClass.QueryParamsResponse other = (irita.opb.QueryOuterClass.QueryParamsResponse) obj;

      boolean result = true;
      result = result && (hasParams() == other.hasParams());
      if (hasParams()) {
        result = result && getParams()
            .equals(other.getParams());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasParams()) {
        hash = (37 * hash) + PARAMS_FIELD_NUMBER;
        hash = (53 * hash) + getParams().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static irita.opb.QueryOuterClass.QueryParamsResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static irita.opb.QueryOuterClass.QueryParamsResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static irita.opb.QueryOuterClass.QueryParamsResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static irita.opb.QueryOuterClass.QueryParamsResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static irita.opb.QueryOuterClass.QueryParamsResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static irita.opb.QueryOuterClass.QueryParamsResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static irita.opb.QueryOuterClass.QueryParamsResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static irita.opb.QueryOuterClass.QueryParamsResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static irita.opb.QueryOuterClass.QueryParamsResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static irita.opb.QueryOuterClass.QueryParamsResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(irita.opb.QueryOuterClass.QueryParamsResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * QueryParamsResponse is the response type for the Query/Params RPC method
     * </pre>
     *
     * Protobuf type {@code irita.opb.QueryParamsResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:irita.opb.QueryParamsResponse)
        irita.opb.QueryOuterClass.QueryParamsResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return irita.opb.QueryOuterClass.internal_static_irita_opb_QueryParamsResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return irita.opb.QueryOuterClass.internal_static_irita_opb_QueryParamsResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                irita.opb.QueryOuterClass.QueryParamsResponse.class, irita.opb.QueryOuterClass.QueryParamsResponse.Builder.class);
      }

      // Construct using irita.opb.QueryOuterClass.QueryParamsResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (paramsBuilder_ == null) {
          params_ = null;
        } else {
          params_ = null;
          paramsBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return irita.opb.QueryOuterClass.internal_static_irita_opb_QueryParamsResponse_descriptor;
      }

      public irita.opb.QueryOuterClass.QueryParamsResponse getDefaultInstanceForType() {
        return irita.opb.QueryOuterClass.QueryParamsResponse.getDefaultInstance();
      }

      public irita.opb.QueryOuterClass.QueryParamsResponse build() {
        irita.opb.QueryOuterClass.QueryParamsResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public irita.opb.QueryOuterClass.QueryParamsResponse buildPartial() {
        irita.opb.QueryOuterClass.QueryParamsResponse result = new irita.opb.QueryOuterClass.QueryParamsResponse(this);
        if (paramsBuilder_ == null) {
          result.params_ = params_;
        } else {
          result.params_ = paramsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof irita.opb.QueryOuterClass.QueryParamsResponse) {
          return mergeFrom((irita.opb.QueryOuterClass.QueryParamsResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(irita.opb.QueryOuterClass.QueryParamsResponse other) {
        if (other == irita.opb.QueryOuterClass.QueryParamsResponse.getDefaultInstance()) return this;
        if (other.hasParams()) {
          mergeParams(other.getParams());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        irita.opb.QueryOuterClass.QueryParamsResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (irita.opb.QueryOuterClass.QueryParamsResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private irita.opb.Opb.Params params_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          irita.opb.Opb.Params, irita.opb.Opb.Params.Builder, irita.opb.Opb.ParamsOrBuilder> paramsBuilder_;
      /**
       * <code>optional .irita.opb.Params params = 1;</code>
       */
      public boolean hasParams() {
        return paramsBuilder_ != null || params_ != null;
      }
      /**
       * <code>optional .irita.opb.Params params = 1;</code>
       */
      public irita.opb.Opb.Params getParams() {
        if (paramsBuilder_ == null) {
          return params_ == null ? irita.opb.Opb.Params.getDefaultInstance() : params_;
        } else {
          return paramsBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .irita.opb.Params params = 1;</code>
       */
      public Builder setParams(irita.opb.Opb.Params value) {
        if (paramsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          params_ = value;
          onChanged();
        } else {
          paramsBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .irita.opb.Params params = 1;</code>
       */
      public Builder setParams(
          irita.opb.Opb.Params.Builder builderForValue) {
        if (paramsBuilder_ == null) {
          params_ = builderForValue.build();
          onChanged();
        } else {
          paramsBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .irita.opb.Params params = 1;</code>
       */
      public Builder mergeParams(irita.opb.Opb.Params value) {
        if (paramsBuilder_ == null) {
          if (params_ != null) {
            params_ =
              irita.opb.Opb.Params.newBuilder(params_).mergeFrom(value).buildPartial();
          } else {
            params_ = value;
          }
          onChanged();
        } else {
          paramsBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .irita.opb.Params params = 1;</code>
       */
      public Builder clearParams() {
        if (paramsBuilder_ == null) {
          params_ = null;
          onChanged();
        } else {
          params_ = null;
          paramsBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .irita.opb.Params params = 1;</code>
       */
      public irita.opb.Opb.Params.Builder getParamsBuilder() {
        
        onChanged();
        return getParamsFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .irita.opb.Params params = 1;</code>
       */
      public irita.opb.Opb.ParamsOrBuilder getParamsOrBuilder() {
        if (paramsBuilder_ != null) {
          return paramsBuilder_.getMessageOrBuilder();
        } else {
          return params_ == null ?
              irita.opb.Opb.Params.getDefaultInstance() : params_;
        }
      }
      /**
       * <code>optional .irita.opb.Params params = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          irita.opb.Opb.Params, irita.opb.Opb.Params.Builder, irita.opb.Opb.ParamsOrBuilder> 
          getParamsFieldBuilder() {
        if (paramsBuilder_ == null) {
          paramsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              irita.opb.Opb.Params, irita.opb.Opb.Params.Builder, irita.opb.Opb.ParamsOrBuilder>(
                  getParams(),
                  getParentForChildren(),
                  isClean());
          params_ = null;
        }
        return paramsBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:irita.opb.QueryParamsResponse)
    }

    // @@protoc_insertion_point(class_scope:irita.opb.QueryParamsResponse)
    private static final irita.opb.QueryOuterClass.QueryParamsResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new irita.opb.QueryOuterClass.QueryParamsResponse();
    }

    public static irita.opb.QueryOuterClass.QueryParamsResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<QueryParamsResponse>
        PARSER = new com.google.protobuf.AbstractParser<QueryParamsResponse>() {
      public QueryParamsResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new QueryParamsResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<QueryParamsResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<QueryParamsResponse> getParserForType() {
      return PARSER;
    }

    public irita.opb.QueryOuterClass.QueryParamsResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_irita_opb_QueryParamsRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_irita_opb_QueryParamsRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_irita_opb_QueryParamsResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_irita_opb_QueryParamsResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017opb/query.proto\022\tirita.opb\032\ropb/opb.pr" +
      "oto\032\024gogoproto/gogo.proto\032\034google/api/an" +
      "notations.proto\"\024\n\022QueryParamsRequest\">\n" +
      "\023QueryParamsResponse\022\'\n\006params\030\001 \001(\0132\021.i" +
      "rita.opb.ParamsB\004\310\336\037\0002k\n\005Query\022b\n\006Params" +
      "\022\035.irita.opb.QueryParamsRequest\032\036.irita." +
      "opb.QueryParamsResponse\"\031\202\323\344\223\002\023\022\021/irita/" +
      "opb/paramsB.Z,github.com/bianjieai/irita" +
      "/modules/opb/typesb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          irita.opb.Opb.getDescriptor(),
          com.google.protobuf.GoGoProtos.getDescriptor(),
          com.google.api.AnnotationsProto.getDescriptor(),
        }, assigner);
    internal_static_irita_opb_QueryParamsRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_irita_opb_QueryParamsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_irita_opb_QueryParamsRequest_descriptor,
        new java.lang.String[] { });
    internal_static_irita_opb_QueryParamsResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_irita_opb_QueryParamsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_irita_opb_QueryParamsResponse_descriptor,
        new java.lang.String[] { "Params", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.protobuf.GoGoProtos.nullable);
    registry.add(com.google.api.AnnotationsProto.http);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    irita.opb.Opb.getDescriptor();
    com.google.protobuf.GoGoProtos.getDescriptor();
    com.google.api.AnnotationsProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
